// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// fraction_to_double
NumericVector fraction_to_double(IntegerVector numerator, IntegerVector denominator);
RcppExport SEXP _gnucashr_fraction_to_double(SEXP numeratorSEXP, SEXP denominatorSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerVector >::type numerator(numeratorSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type denominator(denominatorSEXP);
    rcpp_result_gen = Rcpp::wrap(fraction_to_double(numerator, denominator));
    return rcpp_result_gen;
END_RCPP
}
// double_to_fraction
IntegerMatrix double_to_fraction(NumericVector value, int denom);
RcppExport SEXP _gnucashr_double_to_fraction(SEXP valueSEXP, SEXP denomSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type value(valueSEXP);
    Rcpp::traits::input_parameter< int >::type denom(denomSEXP);
    rcpp_result_gen = Rcpp::wrap(double_to_fraction(value, denom));
    return rcpp_result_gen;
END_RCPP
}
// add_fractions
IntegerMatrix add_fractions(IntegerVector num1, IntegerVector denom1, IntegerVector num2, IntegerVector denom2);
RcppExport SEXP _gnucashr_add_fractions(SEXP num1SEXP, SEXP denom1SEXP, SEXP num2SEXP, SEXP denom2SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerVector >::type num1(num1SEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type denom1(denom1SEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type num2(num2SEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type denom2(denom2SEXP);
    rcpp_result_gen = Rcpp::wrap(add_fractions(num1, denom1, num2, denom2));
    return rcpp_result_gen;
END_RCPP
}
// validate_splits_balance
bool validate_splits_balance(IntegerVector numerators, IntegerVector denominators);
RcppExport SEXP _gnucashr_validate_splits_balance(SEXP numeratorsSEXP, SEXP denominatorsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerVector >::type numerators(numeratorsSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type denominators(denominatorsSEXP);
    rcpp_result_gen = Rcpp::wrap(validate_splits_balance(numerators, denominators));
    return rcpp_result_gen;
END_RCPP
}
// gc_open
SEXP gc_open(std::string path, bool read_only);
RcppExport SEXP _gnucashr_gc_open(SEXP pathSEXP, SEXP read_onlySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type path(pathSEXP);
    Rcpp::traits::input_parameter< bool >::type read_only(read_onlySEXP);
    rcpp_result_gen = Rcpp::wrap(gc_open(path, read_only));
    return rcpp_result_gen;
END_RCPP
}
// gc_close
void gc_close(SEXP book_ptr);
RcppExport SEXP _gnucashr_gc_close(SEXP book_ptrSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type book_ptr(book_ptrSEXP);
    gc_close(book_ptr);
    return R_NilValue;
END_RCPP
}
// gc_info
List gc_info(SEXP book_ptr);
RcppExport SEXP _gnucashr_gc_info(SEXP book_ptrSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type book_ptr(book_ptrSEXP);
    rcpp_result_gen = Rcpp::wrap(gc_info(book_ptr));
    return rcpp_result_gen;
END_RCPP
}
// gc_get_accounts
DataFrame gc_get_accounts(SEXP book_ptr);
RcppExport SEXP _gnucashr_gc_get_accounts(SEXP book_ptrSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type book_ptr(book_ptrSEXP);
    rcpp_result_gen = Rcpp::wrap(gc_get_accounts(book_ptr));
    return rcpp_result_gen;
END_RCPP
}
// gc_account_tree
DataFrame gc_account_tree(SEXP book_ptr);
RcppExport SEXP _gnucashr_gc_account_tree(SEXP book_ptrSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type book_ptr(book_ptrSEXP);
    rcpp_result_gen = Rcpp::wrap(gc_account_tree(book_ptr));
    return rcpp_result_gen;
END_RCPP
}
// gc_get_account
DataFrame gc_get_account(SEXP book_ptr, std::string guid);
RcppExport SEXP _gnucashr_gc_get_account(SEXP book_ptrSEXP, SEXP guidSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type book_ptr(book_ptrSEXP);
    Rcpp::traits::input_parameter< std::string >::type guid(guidSEXP);
    rcpp_result_gen = Rcpp::wrap(gc_get_account(book_ptr, guid));
    return rcpp_result_gen;
END_RCPP
}
// gc_get_account_by_path
DataFrame gc_get_account_by_path(SEXP book_ptr, std::string path);
RcppExport SEXP _gnucashr_gc_get_account_by_path(SEXP book_ptrSEXP, SEXP pathSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type book_ptr(book_ptrSEXP);
    Rcpp::traits::input_parameter< std::string >::type path(pathSEXP);
    rcpp_result_gen = Rcpp::wrap(gc_get_account_by_path(book_ptr, path));
    return rcpp_result_gen;
END_RCPP
}
// gc_get_transactions
DataFrame gc_get_transactions(SEXP book_ptr, Nullable<std::string> from_date, Nullable<std::string> to_date);
RcppExport SEXP _gnucashr_gc_get_transactions(SEXP book_ptrSEXP, SEXP from_dateSEXP, SEXP to_dateSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type book_ptr(book_ptrSEXP);
    Rcpp::traits::input_parameter< Nullable<std::string> >::type from_date(from_dateSEXP);
    Rcpp::traits::input_parameter< Nullable<std::string> >::type to_date(to_dateSEXP);
    rcpp_result_gen = Rcpp::wrap(gc_get_transactions(book_ptr, from_date, to_date));
    return rcpp_result_gen;
END_RCPP
}
// gc_get_balance
double gc_get_balance(SEXP book_ptr, std::string account_guid, Nullable<std::string> as_of);
RcppExport SEXP _gnucashr_gc_get_balance(SEXP book_ptrSEXP, SEXP account_guidSEXP, SEXP as_ofSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type book_ptr(book_ptrSEXP);
    Rcpp::traits::input_parameter< std::string >::type account_guid(account_guidSEXP);
    Rcpp::traits::input_parameter< Nullable<std::string> >::type as_of(as_ofSEXP);
    rcpp_result_gen = Rcpp::wrap(gc_get_balance(book_ptr, account_guid, as_of));
    return rcpp_result_gen;
END_RCPP
}
// gc_trial_balance
DataFrame gc_trial_balance(SEXP book_ptr, Nullable<std::string> as_of);
RcppExport SEXP _gnucashr_gc_trial_balance(SEXP book_ptrSEXP, SEXP as_ofSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type book_ptr(book_ptrSEXP);
    Rcpp::traits::input_parameter< Nullable<std::string> >::type as_of(as_ofSEXP);
    rcpp_result_gen = Rcpp::wrap(gc_trial_balance(book_ptr, as_of));
    return rcpp_result_gen;
END_RCPP
}
// gc_create_account
std::string gc_create_account(SEXP book_ptr, std::string name, std::string type, std::string parent_guid, std::string description, std::string code, bool hidden, bool placeholder);
RcppExport SEXP _gnucashr_gc_create_account(SEXP book_ptrSEXP, SEXP nameSEXP, SEXP typeSEXP, SEXP parent_guidSEXP, SEXP descriptionSEXP, SEXP codeSEXP, SEXP hiddenSEXP, SEXP placeholderSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type book_ptr(book_ptrSEXP);
    Rcpp::traits::input_parameter< std::string >::type name(nameSEXP);
    Rcpp::traits::input_parameter< std::string >::type type(typeSEXP);
    Rcpp::traits::input_parameter< std::string >::type parent_guid(parent_guidSEXP);
    Rcpp::traits::input_parameter< std::string >::type description(descriptionSEXP);
    Rcpp::traits::input_parameter< std::string >::type code(codeSEXP);
    Rcpp::traits::input_parameter< bool >::type hidden(hiddenSEXP);
    Rcpp::traits::input_parameter< bool >::type placeholder(placeholderSEXP);
    rcpp_result_gen = Rcpp::wrap(gc_create_account(book_ptr, name, type, parent_guid, description, code, hidden, placeholder));
    return rcpp_result_gen;
END_RCPP
}
// gc_post_transaction
std::string gc_post_transaction(SEXP book_ptr, std::string description, std::string post_date, DataFrame splits_df, std::string num);
RcppExport SEXP _gnucashr_gc_post_transaction(SEXP book_ptrSEXP, SEXP descriptionSEXP, SEXP post_dateSEXP, SEXP splits_dfSEXP, SEXP numSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type book_ptr(book_ptrSEXP);
    Rcpp::traits::input_parameter< std::string >::type description(descriptionSEXP);
    Rcpp::traits::input_parameter< std::string >::type post_date(post_dateSEXP);
    Rcpp::traits::input_parameter< DataFrame >::type splits_df(splits_dfSEXP);
    Rcpp::traits::input_parameter< std::string >::type num(numSEXP);
    rcpp_result_gen = Rcpp::wrap(gc_post_transaction(book_ptr, description, post_date, splits_df, num));
    return rcpp_result_gen;
END_RCPP
}
// gc_delete_transaction
void gc_delete_transaction(SEXP book_ptr, std::string guid);
RcppExport SEXP _gnucashr_gc_delete_transaction(SEXP book_ptrSEXP, SEXP guidSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type book_ptr(book_ptrSEXP);
    Rcpp::traits::input_parameter< std::string >::type guid(guidSEXP);
    gc_delete_transaction(book_ptr, guid);
    return R_NilValue;
END_RCPP
}
// gc_void_transaction
void gc_void_transaction(SEXP book_ptr, std::string guid, std::string reason);
RcppExport SEXP _gnucashr_gc_void_transaction(SEXP book_ptrSEXP, SEXP guidSEXP, SEXP reasonSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type book_ptr(book_ptrSEXP);
    Rcpp::traits::input_parameter< std::string >::type guid(guidSEXP);
    Rcpp::traits::input_parameter< std::string >::type reason(reasonSEXP);
    gc_void_transaction(book_ptr, guid, reason);
    return R_NilValue;
END_RCPP
}
// gc_update_split
void gc_update_split(SEXP book_ptr, std::string split_guid, std::string new_account_guid);
RcppExport SEXP _gnucashr_gc_update_split(SEXP book_ptrSEXP, SEXP split_guidSEXP, SEXP new_account_guidSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type book_ptr(book_ptrSEXP);
    Rcpp::traits::input_parameter< std::string >::type split_guid(split_guidSEXP);
    Rcpp::traits::input_parameter< std::string >::type new_account_guid(new_account_guidSEXP);
    gc_update_split(book_ptr, split_guid, new_account_guid);
    return R_NilValue;
END_RCPP
}
// gc_get_splits
DataFrame gc_get_splits(SEXP book_ptr, std::string account_guid);
RcppExport SEXP _gnucashr_gc_get_splits(SEXP book_ptrSEXP, SEXP account_guidSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type book_ptr(book_ptrSEXP);
    Rcpp::traits::input_parameter< std::string >::type account_guid(account_guidSEXP);
    rcpp_result_gen = Rcpp::wrap(gc_get_splits(book_ptr, account_guid));
    return rcpp_result_gen;
END_RCPP
}
// gc_parse_csv
DataFrame gc_parse_csv(std::string content, std::string format_name);
RcppExport SEXP _gnucashr_gc_parse_csv(SEXP contentSEXP, SEXP format_nameSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type content(contentSEXP);
    Rcpp::traits::input_parameter< std::string >::type format_name(format_nameSEXP);
    rcpp_result_gen = Rcpp::wrap(gc_parse_csv(content, format_name));
    return rcpp_result_gen;
END_RCPP
}
// gc_detect_csv_format
std::string gc_detect_csv_format(std::string header_line);
RcppExport SEXP _gnucashr_gc_detect_csv_format(SEXP header_lineSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type header_line(header_lineSEXP);
    rcpp_result_gen = Rcpp::wrap(gc_detect_csv_format(header_line));
    return rcpp_result_gen;
END_RCPP
}
// gc_csv_format_info
List gc_csv_format_info(std::string format_name);
RcppExport SEXP _gnucashr_gc_csv_format_info(SEXP format_nameSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type format_name(format_nameSEXP);
    rcpp_result_gen = Rcpp::wrap(gc_csv_format_info(format_name));
    return rcpp_result_gen;
END_RCPP
}
// gc_get_slot
SEXP gc_get_slot(SEXP book_ptr, std::string obj_guid, std::string name);
RcppExport SEXP _gnucashr_gc_get_slot(SEXP book_ptrSEXP, SEXP obj_guidSEXP, SEXP nameSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type book_ptr(book_ptrSEXP);
    Rcpp::traits::input_parameter< std::string >::type obj_guid(obj_guidSEXP);
    Rcpp::traits::input_parameter< std::string >::type name(nameSEXP);
    rcpp_result_gen = Rcpp::wrap(gc_get_slot(book_ptr, obj_guid, name));
    return rcpp_result_gen;
END_RCPP
}
// gc_set_slot
void gc_set_slot(SEXP book_ptr, std::string obj_guid, std::string name, std::string value);
RcppExport SEXP _gnucashr_gc_set_slot(SEXP book_ptrSEXP, SEXP obj_guidSEXP, SEXP nameSEXP, SEXP valueSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type book_ptr(book_ptrSEXP);
    Rcpp::traits::input_parameter< std::string >::type obj_guid(obj_guidSEXP);
    Rcpp::traits::input_parameter< std::string >::type name(nameSEXP);
    Rcpp::traits::input_parameter< std::string >::type value(valueSEXP);
    gc_set_slot(book_ptr, obj_guid, name, value);
    return R_NilValue;
END_RCPP
}
// gc_delete_slot
void gc_delete_slot(SEXP book_ptr, std::string obj_guid, std::string name);
RcppExport SEXP _gnucashr_gc_delete_slot(SEXP book_ptrSEXP, SEXP obj_guidSEXP, SEXP nameSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type book_ptr(book_ptrSEXP);
    Rcpp::traits::input_parameter< std::string >::type obj_guid(obj_guidSEXP);
    Rcpp::traits::input_parameter< std::string >::type name(nameSEXP);
    gc_delete_slot(book_ptr, obj_guid, name);
    return R_NilValue;
END_RCPP
}
// gc_get_all_slots
DataFrame gc_get_all_slots(SEXP book_ptr, std::string obj_guid);
RcppExport SEXP _gnucashr_gc_get_all_slots(SEXP book_ptrSEXP, SEXP obj_guidSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type book_ptr(book_ptrSEXP);
    Rcpp::traits::input_parameter< std::string >::type obj_guid(obj_guidSEXP);
    rcpp_result_gen = Rcpp::wrap(gc_get_all_slots(book_ptr, obj_guid));
    return rcpp_result_gen;
END_RCPP
}
// gc_find_split_by_fitid
std::string gc_find_split_by_fitid(SEXP book_ptr, std::string account_guid, std::string fitid);
RcppExport SEXP _gnucashr_gc_find_split_by_fitid(SEXP book_ptrSEXP, SEXP account_guidSEXP, SEXP fitidSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type book_ptr(book_ptrSEXP);
    Rcpp::traits::input_parameter< std::string >::type account_guid(account_guidSEXP);
    Rcpp::traits::input_parameter< std::string >::type fitid(fitidSEXP);
    rcpp_result_gen = Rcpp::wrap(gc_find_split_by_fitid(book_ptr, account_guid, fitid));
    return rcpp_result_gen;
END_RCPP
}
// gc_check_fitids
DataFrame gc_check_fitids(SEXP book_ptr, std::string account_guid, CharacterVector fitids);
RcppExport SEXP _gnucashr_gc_check_fitids(SEXP book_ptrSEXP, SEXP account_guidSEXP, SEXP fitidsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type book_ptr(book_ptrSEXP);
    Rcpp::traits::input_parameter< std::string >::type account_guid(account_guidSEXP);
    Rcpp::traits::input_parameter< CharacterVector >::type fitids(fitidsSEXP);
    rcpp_result_gen = Rcpp::wrap(gc_check_fitids(book_ptr, account_guid, fitids));
    return rcpp_result_gen;
END_RCPP
}
// gc_import_ofx_feed
List gc_import_ofx_feed(SEXP book_ptr, std::string content, std::string target_account_guid, std::string imbalance_account_guid);
RcppExport SEXP _gnucashr_gc_import_ofx_feed(SEXP book_ptrSEXP, SEXP contentSEXP, SEXP target_account_guidSEXP, SEXP imbalance_account_guidSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type book_ptr(book_ptrSEXP);
    Rcpp::traits::input_parameter< std::string >::type content(contentSEXP);
    Rcpp::traits::input_parameter< std::string >::type target_account_guid(target_account_guidSEXP);
    Rcpp::traits::input_parameter< std::string >::type imbalance_account_guid(imbalance_account_guidSEXP);
    rcpp_result_gen = Rcpp::wrap(gc_import_ofx_feed(book_ptr, content, target_account_guid, imbalance_account_guid));
    return rcpp_result_gen;
END_RCPP
}
// gc_import_csv_feed
List gc_import_csv_feed(SEXP book_ptr, std::string content, std::string format_name, std::string target_account_guid, std::string imbalance_account_guid);
RcppExport SEXP _gnucashr_gc_import_csv_feed(SEXP book_ptrSEXP, SEXP contentSEXP, SEXP format_nameSEXP, SEXP target_account_guidSEXP, SEXP imbalance_account_guidSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type book_ptr(book_ptrSEXP);
    Rcpp::traits::input_parameter< std::string >::type content(contentSEXP);
    Rcpp::traits::input_parameter< std::string >::type format_name(format_nameSEXP);
    Rcpp::traits::input_parameter< std::string >::type target_account_guid(target_account_guidSEXP);
    Rcpp::traits::input_parameter< std::string >::type imbalance_account_guid(imbalance_account_guidSEXP);
    rcpp_result_gen = Rcpp::wrap(gc_import_csv_feed(book_ptr, content, format_name, target_account_guid, imbalance_account_guid));
    return rcpp_result_gen;
END_RCPP
}
// gc_check_duplicates
DataFrame gc_check_duplicates(SEXP book_ptr, std::string account_guid, CharacterVector fitids);
RcppExport SEXP _gnucashr_gc_check_duplicates(SEXP book_ptrSEXP, SEXP account_guidSEXP, SEXP fitidsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type book_ptr(book_ptrSEXP);
    Rcpp::traits::input_parameter< std::string >::type account_guid(account_guidSEXP);
    Rcpp::traits::input_parameter< CharacterVector >::type fitids(fitidsSEXP);
    rcpp_result_gen = Rcpp::wrap(gc_check_duplicates(book_ptr, account_guid, fitids));
    return rcpp_result_gen;
END_RCPP
}
// gc_reconcile_account
List gc_reconcile_account(SEXP book_ptr, std::string account_guid, std::string statement_date, double statement_balance);
RcppExport SEXP _gnucashr_gc_reconcile_account(SEXP book_ptrSEXP, SEXP account_guidSEXP, SEXP statement_dateSEXP, SEXP statement_balanceSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type book_ptr(book_ptrSEXP);
    Rcpp::traits::input_parameter< std::string >::type account_guid(account_guidSEXP);
    Rcpp::traits::input_parameter< std::string >::type statement_date(statement_dateSEXP);
    Rcpp::traits::input_parameter< double >::type statement_balance(statement_balanceSEXP);
    rcpp_result_gen = Rcpp::wrap(gc_reconcile_account(book_ptr, account_guid, statement_date, statement_balance));
    return rcpp_result_gen;
END_RCPP
}
// gc_find_transfer_matches
DataFrame gc_find_transfer_matches(SEXP book_ptr, std::string account_a_guid, std::string account_b_guid, std::string from_date, std::string to_date, int date_window, double min_similarity);
RcppExport SEXP _gnucashr_gc_find_transfer_matches(SEXP book_ptrSEXP, SEXP account_a_guidSEXP, SEXP account_b_guidSEXP, SEXP from_dateSEXP, SEXP to_dateSEXP, SEXP date_windowSEXP, SEXP min_similaritySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type book_ptr(book_ptrSEXP);
    Rcpp::traits::input_parameter< std::string >::type account_a_guid(account_a_guidSEXP);
    Rcpp::traits::input_parameter< std::string >::type account_b_guid(account_b_guidSEXP);
    Rcpp::traits::input_parameter< std::string >::type from_date(from_dateSEXP);
    Rcpp::traits::input_parameter< std::string >::type to_date(to_dateSEXP);
    Rcpp::traits::input_parameter< int >::type date_window(date_windowSEXP);
    Rcpp::traits::input_parameter< double >::type min_similarity(min_similaritySEXP);
    rcpp_result_gen = Rcpp::wrap(gc_find_transfer_matches(book_ptr, account_a_guid, account_b_guid, from_date, to_date, date_window, min_similarity));
    return rcpp_result_gen;
END_RCPP
}
// gc_resolve_identity
List gc_resolve_identity(Nullable<std::string> cli_identity);
RcppExport SEXP _gnucashr_gc_resolve_identity(SEXP cli_identitySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Nullable<std::string> >::type cli_identity(cli_identitySEXP);
    rcpp_result_gen = Rcpp::wrap(gc_resolve_identity(cli_identity));
    return rcpp_result_gen;
END_RCPP
}
// gc_system_username
std::string gc_system_username();
RcppExport SEXP _gnucashr_gc_system_username() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(gc_system_username());
    return rcpp_result_gen;
END_RCPP
}
// gc_audit_open
SEXP gc_audit_open(std::string book_path);
RcppExport SEXP _gnucashr_gc_audit_open(SEXP book_pathSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type book_path(book_pathSEXP);
    rcpp_result_gen = Rcpp::wrap(gc_audit_open(book_path));
    return rcpp_result_gen;
END_RCPP
}
// gc_audit_close
void gc_audit_close(SEXP audit_ptr);
RcppExport SEXP _gnucashr_gc_audit_close(SEXP audit_ptrSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type audit_ptr(audit_ptrSEXP);
    gc_audit_close(audit_ptr);
    return R_NilValue;
END_RCPP
}
// gc_audit_log
void gc_audit_log(SEXP audit_ptr, std::string tool_name, std::string book_path, std::string classification, std::string result_status, Nullable<std::string> entity_guid, Nullable<std::string> error_message, Nullable<int> duration_ms);
RcppExport SEXP _gnucashr_gc_audit_log(SEXP audit_ptrSEXP, SEXP tool_nameSEXP, SEXP book_pathSEXP, SEXP classificationSEXP, SEXP result_statusSEXP, SEXP entity_guidSEXP, SEXP error_messageSEXP, SEXP duration_msSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type audit_ptr(audit_ptrSEXP);
    Rcpp::traits::input_parameter< std::string >::type tool_name(tool_nameSEXP);
    Rcpp::traits::input_parameter< std::string >::type book_path(book_pathSEXP);
    Rcpp::traits::input_parameter< std::string >::type classification(classificationSEXP);
    Rcpp::traits::input_parameter< std::string >::type result_status(result_statusSEXP);
    Rcpp::traits::input_parameter< Nullable<std::string> >::type entity_guid(entity_guidSEXP);
    Rcpp::traits::input_parameter< Nullable<std::string> >::type error_message(error_messageSEXP);
    Rcpp::traits::input_parameter< Nullable<int> >::type duration_ms(duration_msSEXP);
    gc_audit_log(audit_ptr, tool_name, book_path, classification, result_status, entity_guid, error_message, duration_ms);
    return R_NilValue;
END_RCPP
}
// gc_audit_query
DataFrame gc_audit_query(SEXP audit_ptr, Nullable<std::string> since, Nullable<std::string> until, Nullable<std::string> tool_name, int limit);
RcppExport SEXP _gnucashr_gc_audit_query(SEXP audit_ptrSEXP, SEXP sinceSEXP, SEXP untilSEXP, SEXP tool_nameSEXP, SEXP limitSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type audit_ptr(audit_ptrSEXP);
    Rcpp::traits::input_parameter< Nullable<std::string> >::type since(sinceSEXP);
    Rcpp::traits::input_parameter< Nullable<std::string> >::type until(untilSEXP);
    Rcpp::traits::input_parameter< Nullable<std::string> >::type tool_name(tool_nameSEXP);
    Rcpp::traits::input_parameter< int >::type limit(limitSEXP);
    rcpp_result_gen = Rcpp::wrap(gc_audit_query(audit_ptr, since, until, tool_name, limit));
    return rcpp_result_gen;
END_RCPP
}
// gc_audit_export_aperture
std::string gc_audit_export_aperture(SEXP audit_ptr, Nullable<std::string> since, Nullable<std::string> until, int limit);
RcppExport SEXP _gnucashr_gc_audit_export_aperture(SEXP audit_ptrSEXP, SEXP sinceSEXP, SEXP untilSEXP, SEXP limitSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type audit_ptr(audit_ptrSEXP);
    Rcpp::traits::input_parameter< Nullable<std::string> >::type since(sinceSEXP);
    Rcpp::traits::input_parameter< Nullable<std::string> >::type until(untilSEXP);
    Rcpp::traits::input_parameter< int >::type limit(limitSEXP);
    rcpp_result_gen = Rcpp::wrap(gc_audit_export_aperture(audit_ptr, since, until, limit));
    return rcpp_result_gen;
END_RCPP
}
// gc_agent_state_open
SEXP gc_agent_state_open(std::string book_path, std::string agent_name);
RcppExport SEXP _gnucashr_gc_agent_state_open(SEXP book_pathSEXP, SEXP agent_nameSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type book_path(book_pathSEXP);
    Rcpp::traits::input_parameter< std::string >::type agent_name(agent_nameSEXP);
    rcpp_result_gen = Rcpp::wrap(gc_agent_state_open(book_path, agent_name));
    return rcpp_result_gen;
END_RCPP
}
// gc_agent_state_close
void gc_agent_state_close(SEXP state_ptr);
RcppExport SEXP _gnucashr_gc_agent_state_close(SEXP state_ptrSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type state_ptr(state_ptrSEXP);
    gc_agent_state_close(state_ptr);
    return R_NilValue;
END_RCPP
}
// gc_agent_state_set
void gc_agent_state_set(SEXP state_ptr, std::string key, std::string value);
RcppExport SEXP _gnucashr_gc_agent_state_set(SEXP state_ptrSEXP, SEXP keySEXP, SEXP valueSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type state_ptr(state_ptrSEXP);
    Rcpp::traits::input_parameter< std::string >::type key(keySEXP);
    Rcpp::traits::input_parameter< std::string >::type value(valueSEXP);
    gc_agent_state_set(state_ptr, key, value);
    return R_NilValue;
END_RCPP
}
// gc_agent_state_get
SEXP gc_agent_state_get(SEXP state_ptr, std::string key);
RcppExport SEXP _gnucashr_gc_agent_state_get(SEXP state_ptrSEXP, SEXP keySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type state_ptr(state_ptrSEXP);
    Rcpp::traits::input_parameter< std::string >::type key(keySEXP);
    rcpp_result_gen = Rcpp::wrap(gc_agent_state_get(state_ptr, key));
    return rcpp_result_gen;
END_RCPP
}
// gc_agent_state_enqueue_review
int gc_agent_state_enqueue_review(SEXP state_ptr, std::string transaction_guid, std::string suggested_category, double confidence, std::string reason);
RcppExport SEXP _gnucashr_gc_agent_state_enqueue_review(SEXP state_ptrSEXP, SEXP transaction_guidSEXP, SEXP suggested_categorySEXP, SEXP confidenceSEXP, SEXP reasonSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type state_ptr(state_ptrSEXP);
    Rcpp::traits::input_parameter< std::string >::type transaction_guid(transaction_guidSEXP);
    Rcpp::traits::input_parameter< std::string >::type suggested_category(suggested_categorySEXP);
    Rcpp::traits::input_parameter< double >::type confidence(confidenceSEXP);
    Rcpp::traits::input_parameter< std::string >::type reason(reasonSEXP);
    rcpp_result_gen = Rcpp::wrap(gc_agent_state_enqueue_review(state_ptr, transaction_guid, suggested_category, confidence, reason));
    return rcpp_result_gen;
END_RCPP
}
// gc_agent_state_pending_reviews
DataFrame gc_agent_state_pending_reviews(SEXP state_ptr, int limit);
RcppExport SEXP _gnucashr_gc_agent_state_pending_reviews(SEXP state_ptrSEXP, SEXP limitSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type state_ptr(state_ptrSEXP);
    Rcpp::traits::input_parameter< int >::type limit(limitSEXP);
    rcpp_result_gen = Rcpp::wrap(gc_agent_state_pending_reviews(state_ptr, limit));
    return rcpp_result_gen;
END_RCPP
}
// gc_agent_state_update_review
void gc_agent_state_update_review(SEXP state_ptr, int id, std::string status);
RcppExport SEXP _gnucashr_gc_agent_state_update_review(SEXP state_ptrSEXP, SEXP idSEXP, SEXP statusSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type state_ptr(state_ptrSEXP);
    Rcpp::traits::input_parameter< int >::type id(idSEXP);
    Rcpp::traits::input_parameter< std::string >::type status(statusSEXP);
    gc_agent_state_update_review(state_ptr, id, status);
    return R_NilValue;
END_RCPP
}
// generate_guid
String generate_guid();
RcppExport SEXP _gnucashr_generate_guid() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(generate_guid());
    return rcpp_result_gen;
END_RCPP
}
// validate_guid
bool validate_guid(String guid);
RcppExport SEXP _gnucashr_validate_guid(SEXP guidSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< String >::type guid(guidSEXP);
    rcpp_result_gen = Rcpp::wrap(validate_guid(guid));
    return rcpp_result_gen;
END_RCPP
}
// generate_guids
CharacterVector generate_guids(int n);
RcppExport SEXP _gnucashr_generate_guids(SEXP nSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    rcpp_result_gen = Rcpp::wrap(generate_guids(n));
    return rcpp_result_gen;
END_RCPP
}
// monte_carlo_parallel
List monte_carlo_parallel(double base_revenue, double base_expense_rate, int n_sims, int n_periods, double growth_mean, double growth_sd, double expense_mean, double expense_sd, int seed);
RcppExport SEXP _gnucashr_monte_carlo_parallel(SEXP base_revenueSEXP, SEXP base_expense_rateSEXP, SEXP n_simsSEXP, SEXP n_periodsSEXP, SEXP growth_meanSEXP, SEXP growth_sdSEXP, SEXP expense_meanSEXP, SEXP expense_sdSEXP, SEXP seedSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type base_revenue(base_revenueSEXP);
    Rcpp::traits::input_parameter< double >::type base_expense_rate(base_expense_rateSEXP);
    Rcpp::traits::input_parameter< int >::type n_sims(n_simsSEXP);
    Rcpp::traits::input_parameter< int >::type n_periods(n_periodsSEXP);
    Rcpp::traits::input_parameter< double >::type growth_mean(growth_meanSEXP);
    Rcpp::traits::input_parameter< double >::type growth_sd(growth_sdSEXP);
    Rcpp::traits::input_parameter< double >::type expense_mean(expense_meanSEXP);
    Rcpp::traits::input_parameter< double >::type expense_sd(expense_sdSEXP);
    Rcpp::traits::input_parameter< int >::type seed(seedSEXP);
    rcpp_result_gen = Rcpp::wrap(monte_carlo_parallel(base_revenue, base_expense_rate, n_sims, n_periods, growth_mean, growth_sd, expense_mean, expense_sd, seed));
    return rcpp_result_gen;
END_RCPP
}
// monte_carlo_multi_entity
List monte_carlo_multi_entity(NumericVector base_revenues, NumericVector growth_means, NumericVector growth_sds, NumericVector expense_rates, int n_sims, int n_periods, int seed);
RcppExport SEXP _gnucashr_monte_carlo_multi_entity(SEXP base_revenuesSEXP, SEXP growth_meansSEXP, SEXP growth_sdsSEXP, SEXP expense_ratesSEXP, SEXP n_simsSEXP, SEXP n_periodsSEXP, SEXP seedSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type base_revenues(base_revenuesSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type growth_means(growth_meansSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type growth_sds(growth_sdsSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type expense_rates(expense_ratesSEXP);
    Rcpp::traits::input_parameter< int >::type n_sims(n_simsSEXP);
    Rcpp::traits::input_parameter< int >::type n_periods(n_periodsSEXP);
    Rcpp::traits::input_parameter< int >::type seed(seedSEXP);
    rcpp_result_gen = Rcpp::wrap(monte_carlo_multi_entity(base_revenues, growth_means, growth_sds, expense_rates, n_sims, n_periods, seed));
    return rcpp_result_gen;
END_RCPP
}
// detect_ofx_version_cpp
std::string detect_ofx_version_cpp(std::string content);
RcppExport SEXP _gnucashr_detect_ofx_version_cpp(SEXP contentSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type content(contentSEXP);
    rcpp_result_gen = Rcpp::wrap(detect_ofx_version_cpp(content));
    return rcpp_result_gen;
END_RCPP
}
// parse_ofx_cpp
List parse_ofx_cpp(std::string content);
RcppExport SEXP _gnucashr_parse_ofx_cpp(SEXP contentSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type content(contentSEXP);
    rcpp_result_gen = Rcpp::wrap(parse_ofx_cpp(content));
    return rcpp_result_gen;
END_RCPP
}
// extract_ofx_account_info
List extract_ofx_account_info(std::string content);
RcppExport SEXP _gnucashr_extract_ofx_account_info(SEXP contentSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type content(contentSEXP);
    rcpp_result_gen = Rcpp::wrap(extract_ofx_account_info(content));
    return rcpp_result_gen;
END_RCPP
}
// parallel_project_scenarios
List parallel_project_scenarios(NumericVector base_values, NumericMatrix growth_matrix, int n_periods);
RcppExport SEXP _gnucashr_parallel_project_scenarios(SEXP base_valuesSEXP, SEXP growth_matrixSEXP, SEXP n_periodsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type base_values(base_valuesSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type growth_matrix(growth_matrixSEXP);
    Rcpp::traits::input_parameter< int >::type n_periods(n_periodsSEXP);
    rcpp_result_gen = Rcpp::wrap(parallel_project_scenarios(base_values, growth_matrix, n_periods));
    return rcpp_result_gen;
END_RCPP
}
// parallel_sensitivity_grid
List parallel_sensitivity_grid(double base_revenue, double base_expense_rate, NumericVector growth_range, NumericVector expense_range, int n_periods);
RcppExport SEXP _gnucashr_parallel_sensitivity_grid(SEXP base_revenueSEXP, SEXP base_expense_rateSEXP, SEXP growth_rangeSEXP, SEXP expense_rangeSEXP, SEXP n_periodsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type base_revenue(base_revenueSEXP);
    Rcpp::traits::input_parameter< double >::type base_expense_rate(base_expense_rateSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type growth_range(growth_rangeSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type expense_range(expense_rangeSEXP);
    Rcpp::traits::input_parameter< int >::type n_periods(n_periodsSEXP);
    rcpp_result_gen = Rcpp::wrap(parallel_sensitivity_grid(base_revenue, base_expense_rate, growth_range, expense_range, n_periods));
    return rcpp_result_gen;
END_RCPP
}
// batch_project_growth
List batch_project_growth(NumericVector initial_values, double growth_rate, double expense_rate, int n_periods);
RcppExport SEXP _gnucashr_batch_project_growth(SEXP initial_valuesSEXP, SEXP growth_rateSEXP, SEXP expense_rateSEXP, SEXP n_periodsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type initial_values(initial_valuesSEXP);
    Rcpp::traits::input_parameter< double >::type growth_rate(growth_rateSEXP);
    Rcpp::traits::input_parameter< double >::type expense_rate(expense_rateSEXP);
    Rcpp::traits::input_parameter< int >::type n_periods(n_periodsSEXP);
    rcpp_result_gen = Rcpp::wrap(batch_project_growth(initial_values, growth_rate, expense_rate, n_periods));
    return rcpp_result_gen;
END_RCPP
}
// sequential_projection
NumericVector sequential_projection(double base_revenue, double growth_rate, double expense_rate, int n_periods);
RcppExport SEXP _gnucashr_sequential_projection(SEXP base_revenueSEXP, SEXP growth_rateSEXP, SEXP expense_rateSEXP, SEXP n_periodsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type base_revenue(base_revenueSEXP);
    Rcpp::traits::input_parameter< double >::type growth_rate(growth_rateSEXP);
    Rcpp::traits::input_parameter< double >::type expense_rate(expense_rateSEXP);
    Rcpp::traits::input_parameter< int >::type n_periods(n_periodsSEXP);
    rcpp_result_gen = Rcpp::wrap(sequential_projection(base_revenue, growth_rate, expense_rate, n_periods));
    return rcpp_result_gen;
END_RCPP
}
// validate_transaction_balance
List validate_transaction_balance(IntegerVector value_nums, IntegerVector value_denoms, double tolerance);
RcppExport SEXP _gnucashr_validate_transaction_balance(SEXP value_numsSEXP, SEXP value_denomsSEXP, SEXP toleranceSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerVector >::type value_nums(value_numsSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type value_denoms(value_denomsSEXP);
    Rcpp::traits::input_parameter< double >::type tolerance(toleranceSEXP);
    rcpp_result_gen = Rcpp::wrap(validate_transaction_balance(value_nums, value_denoms, tolerance));
    return rcpp_result_gen;
END_RCPP
}
// validate_guids
LogicalVector validate_guids(CharacterVector guids);
RcppExport SEXP _gnucashr_validate_guids(SEXP guidsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< CharacterVector >::type guids(guidsSEXP);
    rcpp_result_gen = Rcpp::wrap(validate_guids(guids));
    return rcpp_result_gen;
END_RCPP
}
// check_guid_uniqueness
List check_guid_uniqueness(CharacterVector guids);
RcppExport SEXP _gnucashr_check_guid_uniqueness(SEXP guidsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< CharacterVector >::type guids(guidsSEXP);
    rcpp_result_gen = Rcpp::wrap(check_guid_uniqueness(guids));
    return rcpp_result_gen;
END_RCPP
}
// validate_split_values
List validate_split_values(IntegerVector value_nums, IntegerVector value_denoms);
RcppExport SEXP _gnucashr_validate_split_values(SEXP value_numsSEXP, SEXP value_denomsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerVector >::type value_nums(value_numsSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type value_denoms(value_denomsSEXP);
    rcpp_result_gen = Rcpp::wrap(validate_split_values(value_nums, value_denoms));
    return rcpp_result_gen;
END_RCPP
}
// calculate_running_balance
NumericVector calculate_running_balance(IntegerVector value_nums, IntegerVector value_denoms, double opening_balance);
RcppExport SEXP _gnucashr_calculate_running_balance(SEXP value_numsSEXP, SEXP value_denomsSEXP, SEXP opening_balanceSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerVector >::type value_nums(value_numsSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type value_denoms(value_denomsSEXP);
    Rcpp::traits::input_parameter< double >::type opening_balance(opening_balanceSEXP);
    rcpp_result_gen = Rcpp::wrap(calculate_running_balance(value_nums, value_denoms, opening_balance));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_gnucashr_fraction_to_double", (DL_FUNC) &_gnucashr_fraction_to_double, 2},
    {"_gnucashr_double_to_fraction", (DL_FUNC) &_gnucashr_double_to_fraction, 2},
    {"_gnucashr_add_fractions", (DL_FUNC) &_gnucashr_add_fractions, 4},
    {"_gnucashr_validate_splits_balance", (DL_FUNC) &_gnucashr_validate_splits_balance, 2},
    {"_gnucashr_gc_open", (DL_FUNC) &_gnucashr_gc_open, 2},
    {"_gnucashr_gc_close", (DL_FUNC) &_gnucashr_gc_close, 1},
    {"_gnucashr_gc_info", (DL_FUNC) &_gnucashr_gc_info, 1},
    {"_gnucashr_gc_get_accounts", (DL_FUNC) &_gnucashr_gc_get_accounts, 1},
    {"_gnucashr_gc_account_tree", (DL_FUNC) &_gnucashr_gc_account_tree, 1},
    {"_gnucashr_gc_get_account", (DL_FUNC) &_gnucashr_gc_get_account, 2},
    {"_gnucashr_gc_get_account_by_path", (DL_FUNC) &_gnucashr_gc_get_account_by_path, 2},
    {"_gnucashr_gc_get_transactions", (DL_FUNC) &_gnucashr_gc_get_transactions, 3},
    {"_gnucashr_gc_get_balance", (DL_FUNC) &_gnucashr_gc_get_balance, 3},
    {"_gnucashr_gc_trial_balance", (DL_FUNC) &_gnucashr_gc_trial_balance, 2},
    {"_gnucashr_gc_create_account", (DL_FUNC) &_gnucashr_gc_create_account, 8},
    {"_gnucashr_gc_post_transaction", (DL_FUNC) &_gnucashr_gc_post_transaction, 5},
    {"_gnucashr_gc_delete_transaction", (DL_FUNC) &_gnucashr_gc_delete_transaction, 2},
    {"_gnucashr_gc_void_transaction", (DL_FUNC) &_gnucashr_gc_void_transaction, 3},
    {"_gnucashr_gc_update_split", (DL_FUNC) &_gnucashr_gc_update_split, 3},
    {"_gnucashr_gc_get_splits", (DL_FUNC) &_gnucashr_gc_get_splits, 2},
    {"_gnucashr_gc_parse_csv", (DL_FUNC) &_gnucashr_gc_parse_csv, 2},
    {"_gnucashr_gc_detect_csv_format", (DL_FUNC) &_gnucashr_gc_detect_csv_format, 1},
    {"_gnucashr_gc_csv_format_info", (DL_FUNC) &_gnucashr_gc_csv_format_info, 1},
    {"_gnucashr_gc_get_slot", (DL_FUNC) &_gnucashr_gc_get_slot, 3},
    {"_gnucashr_gc_set_slot", (DL_FUNC) &_gnucashr_gc_set_slot, 4},
    {"_gnucashr_gc_delete_slot", (DL_FUNC) &_gnucashr_gc_delete_slot, 3},
    {"_gnucashr_gc_get_all_slots", (DL_FUNC) &_gnucashr_gc_get_all_slots, 2},
    {"_gnucashr_gc_find_split_by_fitid", (DL_FUNC) &_gnucashr_gc_find_split_by_fitid, 3},
    {"_gnucashr_gc_check_fitids", (DL_FUNC) &_gnucashr_gc_check_fitids, 3},
    {"_gnucashr_gc_import_ofx_feed", (DL_FUNC) &_gnucashr_gc_import_ofx_feed, 4},
    {"_gnucashr_gc_import_csv_feed", (DL_FUNC) &_gnucashr_gc_import_csv_feed, 5},
    {"_gnucashr_gc_check_duplicates", (DL_FUNC) &_gnucashr_gc_check_duplicates, 3},
    {"_gnucashr_gc_reconcile_account", (DL_FUNC) &_gnucashr_gc_reconcile_account, 4},
    {"_gnucashr_gc_find_transfer_matches", (DL_FUNC) &_gnucashr_gc_find_transfer_matches, 7},
    {"_gnucashr_gc_resolve_identity", (DL_FUNC) &_gnucashr_gc_resolve_identity, 1},
    {"_gnucashr_gc_system_username", (DL_FUNC) &_gnucashr_gc_system_username, 0},
    {"_gnucashr_gc_audit_open", (DL_FUNC) &_gnucashr_gc_audit_open, 1},
    {"_gnucashr_gc_audit_close", (DL_FUNC) &_gnucashr_gc_audit_close, 1},
    {"_gnucashr_gc_audit_log", (DL_FUNC) &_gnucashr_gc_audit_log, 8},
    {"_gnucashr_gc_audit_query", (DL_FUNC) &_gnucashr_gc_audit_query, 5},
    {"_gnucashr_gc_audit_export_aperture", (DL_FUNC) &_gnucashr_gc_audit_export_aperture, 4},
    {"_gnucashr_gc_agent_state_open", (DL_FUNC) &_gnucashr_gc_agent_state_open, 2},
    {"_gnucashr_gc_agent_state_close", (DL_FUNC) &_gnucashr_gc_agent_state_close, 1},
    {"_gnucashr_gc_agent_state_set", (DL_FUNC) &_gnucashr_gc_agent_state_set, 3},
    {"_gnucashr_gc_agent_state_get", (DL_FUNC) &_gnucashr_gc_agent_state_get, 2},
    {"_gnucashr_gc_agent_state_enqueue_review", (DL_FUNC) &_gnucashr_gc_agent_state_enqueue_review, 5},
    {"_gnucashr_gc_agent_state_pending_reviews", (DL_FUNC) &_gnucashr_gc_agent_state_pending_reviews, 2},
    {"_gnucashr_gc_agent_state_update_review", (DL_FUNC) &_gnucashr_gc_agent_state_update_review, 3},
    {"_gnucashr_generate_guid", (DL_FUNC) &_gnucashr_generate_guid, 0},
    {"_gnucashr_validate_guid", (DL_FUNC) &_gnucashr_validate_guid, 1},
    {"_gnucashr_generate_guids", (DL_FUNC) &_gnucashr_generate_guids, 1},
    {"_gnucashr_monte_carlo_parallel", (DL_FUNC) &_gnucashr_monte_carlo_parallel, 9},
    {"_gnucashr_monte_carlo_multi_entity", (DL_FUNC) &_gnucashr_monte_carlo_multi_entity, 7},
    {"_gnucashr_detect_ofx_version_cpp", (DL_FUNC) &_gnucashr_detect_ofx_version_cpp, 1},
    {"_gnucashr_parse_ofx_cpp", (DL_FUNC) &_gnucashr_parse_ofx_cpp, 1},
    {"_gnucashr_extract_ofx_account_info", (DL_FUNC) &_gnucashr_extract_ofx_account_info, 1},
    {"_gnucashr_parallel_project_scenarios", (DL_FUNC) &_gnucashr_parallel_project_scenarios, 3},
    {"_gnucashr_parallel_sensitivity_grid", (DL_FUNC) &_gnucashr_parallel_sensitivity_grid, 5},
    {"_gnucashr_batch_project_growth", (DL_FUNC) &_gnucashr_batch_project_growth, 4},
    {"_gnucashr_sequential_projection", (DL_FUNC) &_gnucashr_sequential_projection, 4},
    {"_gnucashr_validate_transaction_balance", (DL_FUNC) &_gnucashr_validate_transaction_balance, 3},
    {"_gnucashr_validate_guids", (DL_FUNC) &_gnucashr_validate_guids, 1},
    {"_gnucashr_check_guid_uniqueness", (DL_FUNC) &_gnucashr_check_guid_uniqueness, 1},
    {"_gnucashr_validate_split_values", (DL_FUNC) &_gnucashr_validate_split_values, 2},
    {"_gnucashr_calculate_running_balance", (DL_FUNC) &_gnucashr_calculate_running_balance, 3},
    {NULL, NULL, 0}
};

RcppExport void R_init_gnucashr(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
