// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// fraction_to_double
NumericVector fraction_to_double(IntegerVector numerator, IntegerVector denominator);
RcppExport SEXP _gnucashr_fraction_to_double(SEXP numeratorSEXP, SEXP denominatorSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerVector >::type numerator(numeratorSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type denominator(denominatorSEXP);
    rcpp_result_gen = Rcpp::wrap(fraction_to_double(numerator, denominator));
    return rcpp_result_gen;
END_RCPP
}
// double_to_fraction
IntegerMatrix double_to_fraction(NumericVector value, int denom);
RcppExport SEXP _gnucashr_double_to_fraction(SEXP valueSEXP, SEXP denomSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type value(valueSEXP);
    Rcpp::traits::input_parameter< int >::type denom(denomSEXP);
    rcpp_result_gen = Rcpp::wrap(double_to_fraction(value, denom));
    return rcpp_result_gen;
END_RCPP
}
// add_fractions
IntegerMatrix add_fractions(IntegerVector num1, IntegerVector denom1, IntegerVector num2, IntegerVector denom2);
RcppExport SEXP _gnucashr_add_fractions(SEXP num1SEXP, SEXP denom1SEXP, SEXP num2SEXP, SEXP denom2SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerVector >::type num1(num1SEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type denom1(denom1SEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type num2(num2SEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type denom2(denom2SEXP);
    rcpp_result_gen = Rcpp::wrap(add_fractions(num1, denom1, num2, denom2));
    return rcpp_result_gen;
END_RCPP
}
// validate_splits_balance
bool validate_splits_balance(IntegerVector numerators, IntegerVector denominators);
RcppExport SEXP _gnucashr_validate_splits_balance(SEXP numeratorsSEXP, SEXP denominatorsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerVector >::type numerators(numeratorsSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type denominators(denominatorsSEXP);
    rcpp_result_gen = Rcpp::wrap(validate_splits_balance(numerators, denominators));
    return rcpp_result_gen;
END_RCPP
}
// gc_open
SEXP gc_open(std::string path, bool read_only);
RcppExport SEXP _gnucashr_gc_open(SEXP pathSEXP, SEXP read_onlySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type path(pathSEXP);
    Rcpp::traits::input_parameter< bool >::type read_only(read_onlySEXP);
    rcpp_result_gen = Rcpp::wrap(gc_open(path, read_only));
    return rcpp_result_gen;
END_RCPP
}
// gc_close
void gc_close(SEXP book_ptr);
RcppExport SEXP _gnucashr_gc_close(SEXP book_ptrSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type book_ptr(book_ptrSEXP);
    gc_close(book_ptr);
    return R_NilValue;
END_RCPP
}
// gc_info
List gc_info(SEXP book_ptr);
RcppExport SEXP _gnucashr_gc_info(SEXP book_ptrSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type book_ptr(book_ptrSEXP);
    rcpp_result_gen = Rcpp::wrap(gc_info(book_ptr));
    return rcpp_result_gen;
END_RCPP
}
// gc_get_accounts
DataFrame gc_get_accounts(SEXP book_ptr);
RcppExport SEXP _gnucashr_gc_get_accounts(SEXP book_ptrSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type book_ptr(book_ptrSEXP);
    rcpp_result_gen = Rcpp::wrap(gc_get_accounts(book_ptr));
    return rcpp_result_gen;
END_RCPP
}
// gc_account_tree
DataFrame gc_account_tree(SEXP book_ptr);
RcppExport SEXP _gnucashr_gc_account_tree(SEXP book_ptrSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type book_ptr(book_ptrSEXP);
    rcpp_result_gen = Rcpp::wrap(gc_account_tree(book_ptr));
    return rcpp_result_gen;
END_RCPP
}
// gc_get_account
DataFrame gc_get_account(SEXP book_ptr, std::string guid);
RcppExport SEXP _gnucashr_gc_get_account(SEXP book_ptrSEXP, SEXP guidSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type book_ptr(book_ptrSEXP);
    Rcpp::traits::input_parameter< std::string >::type guid(guidSEXP);
    rcpp_result_gen = Rcpp::wrap(gc_get_account(book_ptr, guid));
    return rcpp_result_gen;
END_RCPP
}
// gc_get_account_by_path
DataFrame gc_get_account_by_path(SEXP book_ptr, std::string path);
RcppExport SEXP _gnucashr_gc_get_account_by_path(SEXP book_ptrSEXP, SEXP pathSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type book_ptr(book_ptrSEXP);
    Rcpp::traits::input_parameter< std::string >::type path(pathSEXP);
    rcpp_result_gen = Rcpp::wrap(gc_get_account_by_path(book_ptr, path));
    return rcpp_result_gen;
END_RCPP
}
// gc_get_transactions
DataFrame gc_get_transactions(SEXP book_ptr, Nullable<std::string> from_date, Nullable<std::string> to_date);
RcppExport SEXP _gnucashr_gc_get_transactions(SEXP book_ptrSEXP, SEXP from_dateSEXP, SEXP to_dateSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type book_ptr(book_ptrSEXP);
    Rcpp::traits::input_parameter< Nullable<std::string> >::type from_date(from_dateSEXP);
    Rcpp::traits::input_parameter< Nullable<std::string> >::type to_date(to_dateSEXP);
    rcpp_result_gen = Rcpp::wrap(gc_get_transactions(book_ptr, from_date, to_date));
    return rcpp_result_gen;
END_RCPP
}
// gc_get_balance
double gc_get_balance(SEXP book_ptr, std::string account_guid, Nullable<std::string> as_of);
RcppExport SEXP _gnucashr_gc_get_balance(SEXP book_ptrSEXP, SEXP account_guidSEXP, SEXP as_ofSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type book_ptr(book_ptrSEXP);
    Rcpp::traits::input_parameter< std::string >::type account_guid(account_guidSEXP);
    Rcpp::traits::input_parameter< Nullable<std::string> >::type as_of(as_ofSEXP);
    rcpp_result_gen = Rcpp::wrap(gc_get_balance(book_ptr, account_guid, as_of));
    return rcpp_result_gen;
END_RCPP
}
// gc_trial_balance
DataFrame gc_trial_balance(SEXP book_ptr, Nullable<std::string> as_of);
RcppExport SEXP _gnucashr_gc_trial_balance(SEXP book_ptrSEXP, SEXP as_ofSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type book_ptr(book_ptrSEXP);
    Rcpp::traits::input_parameter< Nullable<std::string> >::type as_of(as_ofSEXP);
    rcpp_result_gen = Rcpp::wrap(gc_trial_balance(book_ptr, as_of));
    return rcpp_result_gen;
END_RCPP
}
// gc_create_account
std::string gc_create_account(SEXP book_ptr, std::string name, std::string type, std::string parent_guid, std::string description, std::string code, bool hidden, bool placeholder);
RcppExport SEXP _gnucashr_gc_create_account(SEXP book_ptrSEXP, SEXP nameSEXP, SEXP typeSEXP, SEXP parent_guidSEXP, SEXP descriptionSEXP, SEXP codeSEXP, SEXP hiddenSEXP, SEXP placeholderSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type book_ptr(book_ptrSEXP);
    Rcpp::traits::input_parameter< std::string >::type name(nameSEXP);
    Rcpp::traits::input_parameter< std::string >::type type(typeSEXP);
    Rcpp::traits::input_parameter< std::string >::type parent_guid(parent_guidSEXP);
    Rcpp::traits::input_parameter< std::string >::type description(descriptionSEXP);
    Rcpp::traits::input_parameter< std::string >::type code(codeSEXP);
    Rcpp::traits::input_parameter< bool >::type hidden(hiddenSEXP);
    Rcpp::traits::input_parameter< bool >::type placeholder(placeholderSEXP);
    rcpp_result_gen = Rcpp::wrap(gc_create_account(book_ptr, name, type, parent_guid, description, code, hidden, placeholder));
    return rcpp_result_gen;
END_RCPP
}
// gc_post_transaction
std::string gc_post_transaction(SEXP book_ptr, std::string description, std::string post_date, DataFrame splits_df, std::string num);
RcppExport SEXP _gnucashr_gc_post_transaction(SEXP book_ptrSEXP, SEXP descriptionSEXP, SEXP post_dateSEXP, SEXP splits_dfSEXP, SEXP numSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type book_ptr(book_ptrSEXP);
    Rcpp::traits::input_parameter< std::string >::type description(descriptionSEXP);
    Rcpp::traits::input_parameter< std::string >::type post_date(post_dateSEXP);
    Rcpp::traits::input_parameter< DataFrame >::type splits_df(splits_dfSEXP);
    Rcpp::traits::input_parameter< std::string >::type num(numSEXP);
    rcpp_result_gen = Rcpp::wrap(gc_post_transaction(book_ptr, description, post_date, splits_df, num));
    return rcpp_result_gen;
END_RCPP
}
// gc_delete_transaction
void gc_delete_transaction(SEXP book_ptr, std::string guid);
RcppExport SEXP _gnucashr_gc_delete_transaction(SEXP book_ptrSEXP, SEXP guidSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type book_ptr(book_ptrSEXP);
    Rcpp::traits::input_parameter< std::string >::type guid(guidSEXP);
    gc_delete_transaction(book_ptr, guid);
    return R_NilValue;
END_RCPP
}
// gc_void_transaction
void gc_void_transaction(SEXP book_ptr, std::string guid, std::string reason);
RcppExport SEXP _gnucashr_gc_void_transaction(SEXP book_ptrSEXP, SEXP guidSEXP, SEXP reasonSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type book_ptr(book_ptrSEXP);
    Rcpp::traits::input_parameter< std::string >::type guid(guidSEXP);
    Rcpp::traits::input_parameter< std::string >::type reason(reasonSEXP);
    gc_void_transaction(book_ptr, guid, reason);
    return R_NilValue;
END_RCPP
}
// generate_guid
String generate_guid();
RcppExport SEXP _gnucashr_generate_guid() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(generate_guid());
    return rcpp_result_gen;
END_RCPP
}
// validate_guid
bool validate_guid(String guid);
RcppExport SEXP _gnucashr_validate_guid(SEXP guidSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< String >::type guid(guidSEXP);
    rcpp_result_gen = Rcpp::wrap(validate_guid(guid));
    return rcpp_result_gen;
END_RCPP
}
// generate_guids
CharacterVector generate_guids(int n);
RcppExport SEXP _gnucashr_generate_guids(SEXP nSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    rcpp_result_gen = Rcpp::wrap(generate_guids(n));
    return rcpp_result_gen;
END_RCPP
}
// monte_carlo_parallel
List monte_carlo_parallel(double base_revenue, double base_expense_rate, int n_sims, int n_periods, double growth_mean, double growth_sd, double expense_mean, double expense_sd, int seed);
RcppExport SEXP _gnucashr_monte_carlo_parallel(SEXP base_revenueSEXP, SEXP base_expense_rateSEXP, SEXP n_simsSEXP, SEXP n_periodsSEXP, SEXP growth_meanSEXP, SEXP growth_sdSEXP, SEXP expense_meanSEXP, SEXP expense_sdSEXP, SEXP seedSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type base_revenue(base_revenueSEXP);
    Rcpp::traits::input_parameter< double >::type base_expense_rate(base_expense_rateSEXP);
    Rcpp::traits::input_parameter< int >::type n_sims(n_simsSEXP);
    Rcpp::traits::input_parameter< int >::type n_periods(n_periodsSEXP);
    Rcpp::traits::input_parameter< double >::type growth_mean(growth_meanSEXP);
    Rcpp::traits::input_parameter< double >::type growth_sd(growth_sdSEXP);
    Rcpp::traits::input_parameter< double >::type expense_mean(expense_meanSEXP);
    Rcpp::traits::input_parameter< double >::type expense_sd(expense_sdSEXP);
    Rcpp::traits::input_parameter< int >::type seed(seedSEXP);
    rcpp_result_gen = Rcpp::wrap(monte_carlo_parallel(base_revenue, base_expense_rate, n_sims, n_periods, growth_mean, growth_sd, expense_mean, expense_sd, seed));
    return rcpp_result_gen;
END_RCPP
}
// monte_carlo_multi_entity
List monte_carlo_multi_entity(NumericVector base_revenues, NumericVector growth_means, NumericVector growth_sds, NumericVector expense_rates, int n_sims, int n_periods, int seed);
RcppExport SEXP _gnucashr_monte_carlo_multi_entity(SEXP base_revenuesSEXP, SEXP growth_meansSEXP, SEXP growth_sdsSEXP, SEXP expense_ratesSEXP, SEXP n_simsSEXP, SEXP n_periodsSEXP, SEXP seedSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type base_revenues(base_revenuesSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type growth_means(growth_meansSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type growth_sds(growth_sdsSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type expense_rates(expense_ratesSEXP);
    Rcpp::traits::input_parameter< int >::type n_sims(n_simsSEXP);
    Rcpp::traits::input_parameter< int >::type n_periods(n_periodsSEXP);
    Rcpp::traits::input_parameter< int >::type seed(seedSEXP);
    rcpp_result_gen = Rcpp::wrap(monte_carlo_multi_entity(base_revenues, growth_means, growth_sds, expense_rates, n_sims, n_periods, seed));
    return rcpp_result_gen;
END_RCPP
}
// detect_ofx_version_cpp
std::string detect_ofx_version_cpp(std::string content);
RcppExport SEXP _gnucashr_detect_ofx_version_cpp(SEXP contentSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type content(contentSEXP);
    rcpp_result_gen = Rcpp::wrap(detect_ofx_version_cpp(content));
    return rcpp_result_gen;
END_RCPP
}
// parse_ofx_cpp
List parse_ofx_cpp(std::string content);
RcppExport SEXP _gnucashr_parse_ofx_cpp(SEXP contentSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type content(contentSEXP);
    rcpp_result_gen = Rcpp::wrap(parse_ofx_cpp(content));
    return rcpp_result_gen;
END_RCPP
}
// extract_ofx_account_info
List extract_ofx_account_info(std::string content);
RcppExport SEXP _gnucashr_extract_ofx_account_info(SEXP contentSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type content(contentSEXP);
    rcpp_result_gen = Rcpp::wrap(extract_ofx_account_info(content));
    return rcpp_result_gen;
END_RCPP
}
// parallel_project_scenarios
List parallel_project_scenarios(NumericVector base_values, NumericMatrix growth_matrix, int n_periods);
RcppExport SEXP _gnucashr_parallel_project_scenarios(SEXP base_valuesSEXP, SEXP growth_matrixSEXP, SEXP n_periodsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type base_values(base_valuesSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type growth_matrix(growth_matrixSEXP);
    Rcpp::traits::input_parameter< int >::type n_periods(n_periodsSEXP);
    rcpp_result_gen = Rcpp::wrap(parallel_project_scenarios(base_values, growth_matrix, n_periods));
    return rcpp_result_gen;
END_RCPP
}
// parallel_sensitivity_grid
List parallel_sensitivity_grid(double base_revenue, double base_expense_rate, NumericVector growth_range, NumericVector expense_range, int n_periods);
RcppExport SEXP _gnucashr_parallel_sensitivity_grid(SEXP base_revenueSEXP, SEXP base_expense_rateSEXP, SEXP growth_rangeSEXP, SEXP expense_rangeSEXP, SEXP n_periodsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type base_revenue(base_revenueSEXP);
    Rcpp::traits::input_parameter< double >::type base_expense_rate(base_expense_rateSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type growth_range(growth_rangeSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type expense_range(expense_rangeSEXP);
    Rcpp::traits::input_parameter< int >::type n_periods(n_periodsSEXP);
    rcpp_result_gen = Rcpp::wrap(parallel_sensitivity_grid(base_revenue, base_expense_rate, growth_range, expense_range, n_periods));
    return rcpp_result_gen;
END_RCPP
}
// batch_project_growth
List batch_project_growth(NumericVector initial_values, double growth_rate, double expense_rate, int n_periods);
RcppExport SEXP _gnucashr_batch_project_growth(SEXP initial_valuesSEXP, SEXP growth_rateSEXP, SEXP expense_rateSEXP, SEXP n_periodsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type initial_values(initial_valuesSEXP);
    Rcpp::traits::input_parameter< double >::type growth_rate(growth_rateSEXP);
    Rcpp::traits::input_parameter< double >::type expense_rate(expense_rateSEXP);
    Rcpp::traits::input_parameter< int >::type n_periods(n_periodsSEXP);
    rcpp_result_gen = Rcpp::wrap(batch_project_growth(initial_values, growth_rate, expense_rate, n_periods));
    return rcpp_result_gen;
END_RCPP
}
// sequential_projection
NumericVector sequential_projection(double base_revenue, double growth_rate, double expense_rate, int n_periods);
RcppExport SEXP _gnucashr_sequential_projection(SEXP base_revenueSEXP, SEXP growth_rateSEXP, SEXP expense_rateSEXP, SEXP n_periodsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type base_revenue(base_revenueSEXP);
    Rcpp::traits::input_parameter< double >::type growth_rate(growth_rateSEXP);
    Rcpp::traits::input_parameter< double >::type expense_rate(expense_rateSEXP);
    Rcpp::traits::input_parameter< int >::type n_periods(n_periodsSEXP);
    rcpp_result_gen = Rcpp::wrap(sequential_projection(base_revenue, growth_rate, expense_rate, n_periods));
    return rcpp_result_gen;
END_RCPP
}
// validate_transaction_balance
List validate_transaction_balance(IntegerVector value_nums, IntegerVector value_denoms, double tolerance);
RcppExport SEXP _gnucashr_validate_transaction_balance(SEXP value_numsSEXP, SEXP value_denomsSEXP, SEXP toleranceSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerVector >::type value_nums(value_numsSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type value_denoms(value_denomsSEXP);
    Rcpp::traits::input_parameter< double >::type tolerance(toleranceSEXP);
    rcpp_result_gen = Rcpp::wrap(validate_transaction_balance(value_nums, value_denoms, tolerance));
    return rcpp_result_gen;
END_RCPP
}
// validate_guids
LogicalVector validate_guids(CharacterVector guids);
RcppExport SEXP _gnucashr_validate_guids(SEXP guidsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< CharacterVector >::type guids(guidsSEXP);
    rcpp_result_gen = Rcpp::wrap(validate_guids(guids));
    return rcpp_result_gen;
END_RCPP
}
// check_guid_uniqueness
List check_guid_uniqueness(CharacterVector guids);
RcppExport SEXP _gnucashr_check_guid_uniqueness(SEXP guidsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< CharacterVector >::type guids(guidsSEXP);
    rcpp_result_gen = Rcpp::wrap(check_guid_uniqueness(guids));
    return rcpp_result_gen;
END_RCPP
}
// validate_split_values
List validate_split_values(IntegerVector value_nums, IntegerVector value_denoms);
RcppExport SEXP _gnucashr_validate_split_values(SEXP value_numsSEXP, SEXP value_denomsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerVector >::type value_nums(value_numsSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type value_denoms(value_denomsSEXP);
    rcpp_result_gen = Rcpp::wrap(validate_split_values(value_nums, value_denoms));
    return rcpp_result_gen;
END_RCPP
}
// calculate_running_balance
NumericVector calculate_running_balance(IntegerVector value_nums, IntegerVector value_denoms, double opening_balance);
RcppExport SEXP _gnucashr_calculate_running_balance(SEXP value_numsSEXP, SEXP value_denomsSEXP, SEXP opening_balanceSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerVector >::type value_nums(value_numsSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type value_denoms(value_denomsSEXP);
    Rcpp::traits::input_parameter< double >::type opening_balance(opening_balanceSEXP);
    rcpp_result_gen = Rcpp::wrap(calculate_running_balance(value_nums, value_denoms, opening_balance));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_gnucashr_fraction_to_double", (DL_FUNC) &_gnucashr_fraction_to_double, 2},
    {"_gnucashr_double_to_fraction", (DL_FUNC) &_gnucashr_double_to_fraction, 2},
    {"_gnucashr_add_fractions", (DL_FUNC) &_gnucashr_add_fractions, 4},
    {"_gnucashr_validate_splits_balance", (DL_FUNC) &_gnucashr_validate_splits_balance, 2},
    {"_gnucashr_gc_open", (DL_FUNC) &_gnucashr_gc_open, 2},
    {"_gnucashr_gc_close", (DL_FUNC) &_gnucashr_gc_close, 1},
    {"_gnucashr_gc_info", (DL_FUNC) &_gnucashr_gc_info, 1},
    {"_gnucashr_gc_get_accounts", (DL_FUNC) &_gnucashr_gc_get_accounts, 1},
    {"_gnucashr_gc_account_tree", (DL_FUNC) &_gnucashr_gc_account_tree, 1},
    {"_gnucashr_gc_get_account", (DL_FUNC) &_gnucashr_gc_get_account, 2},
    {"_gnucashr_gc_get_account_by_path", (DL_FUNC) &_gnucashr_gc_get_account_by_path, 2},
    {"_gnucashr_gc_get_transactions", (DL_FUNC) &_gnucashr_gc_get_transactions, 3},
    {"_gnucashr_gc_get_balance", (DL_FUNC) &_gnucashr_gc_get_balance, 3},
    {"_gnucashr_gc_trial_balance", (DL_FUNC) &_gnucashr_gc_trial_balance, 2},
    {"_gnucashr_gc_create_account", (DL_FUNC) &_gnucashr_gc_create_account, 8},
    {"_gnucashr_gc_post_transaction", (DL_FUNC) &_gnucashr_gc_post_transaction, 5},
    {"_gnucashr_gc_delete_transaction", (DL_FUNC) &_gnucashr_gc_delete_transaction, 2},
    {"_gnucashr_gc_void_transaction", (DL_FUNC) &_gnucashr_gc_void_transaction, 3},
    {"_gnucashr_generate_guid", (DL_FUNC) &_gnucashr_generate_guid, 0},
    {"_gnucashr_validate_guid", (DL_FUNC) &_gnucashr_validate_guid, 1},
    {"_gnucashr_generate_guids", (DL_FUNC) &_gnucashr_generate_guids, 1},
    {"_gnucashr_monte_carlo_parallel", (DL_FUNC) &_gnucashr_monte_carlo_parallel, 9},
    {"_gnucashr_monte_carlo_multi_entity", (DL_FUNC) &_gnucashr_monte_carlo_multi_entity, 7},
    {"_gnucashr_detect_ofx_version_cpp", (DL_FUNC) &_gnucashr_detect_ofx_version_cpp, 1},
    {"_gnucashr_parse_ofx_cpp", (DL_FUNC) &_gnucashr_parse_ofx_cpp, 1},
    {"_gnucashr_extract_ofx_account_info", (DL_FUNC) &_gnucashr_extract_ofx_account_info, 1},
    {"_gnucashr_parallel_project_scenarios", (DL_FUNC) &_gnucashr_parallel_project_scenarios, 3},
    {"_gnucashr_parallel_sensitivity_grid", (DL_FUNC) &_gnucashr_parallel_sensitivity_grid, 5},
    {"_gnucashr_batch_project_growth", (DL_FUNC) &_gnucashr_batch_project_growth, 4},
    {"_gnucashr_sequential_projection", (DL_FUNC) &_gnucashr_sequential_projection, 4},
    {"_gnucashr_validate_transaction_balance", (DL_FUNC) &_gnucashr_validate_transaction_balance, 3},
    {"_gnucashr_validate_guids", (DL_FUNC) &_gnucashr_validate_guids, 1},
    {"_gnucashr_check_guid_uniqueness", (DL_FUNC) &_gnucashr_check_guid_uniqueness, 1},
    {"_gnucashr_validate_split_values", (DL_FUNC) &_gnucashr_validate_split_values, 2},
    {"_gnucashr_calculate_running_balance", (DL_FUNC) &_gnucashr_calculate_running_balance, 3},
    {NULL, NULL, 0}
};

RcppExport void R_init_gnucashr(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
