# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Convert Fractions to Double
#'
#' Vectorized conversion of GnuCash fraction representation to double.
#' This is a hot path in balance calculations, hence Rcpp implementation.
#'
#' @param numerator Integer vector of numerators (value_num)
#' @param denominator Integer vector of denominators (value_denom)
#' @return NumericVector of double values
#' @export
fraction_to_double <- function(numerator, denominator) {
    .Call(`_gnucashr_fraction_to_double`, numerator, denominator)
}

#' Convert Double to Fraction
#'
#' Convert decimal values to fractions with specified precision.
#' Default denominator of 100 for currency (cents precision).
#'
#' @param value NumericVector of decimal values
#' @param denom Target denominator (default 100 for cents)
#' @return IntegerMatrix with columns: numerator, denominator
#' @export
double_to_fraction <- function(value, denom = 100L) {
    .Call(`_gnucashr_double_to_fraction`, value, denom)
}

#' Add Two Fractions
#'
#' Vectorized fraction addition maintaining exact representation.
#' Used for accumulating balances without floating-point drift.
#'
#' @param num1 First numerator vector
#' @param denom1 First denominator vector
#' @param num2 Second numerator vector
#' @param denom2 Second denominator vector
#' @return IntegerMatrix with columns: numerator, denominator
#' @export
add_fractions <- function(num1, denom1, num2, denom2) {
    .Call(`_gnucashr_add_fractions`, num1, denom1, num2, denom2)
}

#' Validate Splits Balance
#'
#' Verify that splits in a transaction sum to zero (double-entry principle).
#' Returns TRUE if balanced, FALSE otherwise.
#'
#' @param numerators Integer vector of split value_num
#' @param denominators Integer vector of split value_denom
#' @return Logical indicating if splits balance to zero
#' @export
validate_splits_balance <- function(numerators, denominators) {
    .Call(`_gnucashr_validate_splits_balance`, numerators, denominators)
}

#' Open a GnuCash SQLite Database (C++ Backend)
#'
#' Opens a GnuCash SQLite database file using the native C++ library,
#' returning an external pointer handle for subsequent operations.
#'
#' @param path Path to .gnucash SQLite database file
#' @param read_only Open in read-only mode (default TRUE)
#' @return External pointer to Book object
#' @export
gc_open <- function(path, read_only = TRUE) {
    .Call(`_gnucashr_gc_open`, path, read_only)
}

#' Close a GnuCash Database Handle
#'
#' @param book_ptr External pointer from gc_open()
#' @export
gc_close <- function(book_ptr) {
    invisible(.Call(`_gnucashr_gc_close`, book_ptr))
}

#' Get Book Metadata
#'
#' @param book_ptr External pointer from gc_open()
#' @return Named list with book_guid, root_account_guid, default_currency, read_only
#' @export
gc_info <- function(book_ptr) {
    .Call(`_gnucashr_gc_info`, book_ptr)
}

#' Get All Accounts (C++ Backend)
#'
#' @param book_ptr External pointer from gc_open()
#' @return Data frame of accounts
#' @export
gc_get_accounts <- function(book_ptr) {
    .Call(`_gnucashr_gc_get_accounts`, book_ptr)
}

#' Get Account Tree with Full Paths (C++ Backend)
#'
#' @param book_ptr External pointer from gc_open()
#' @return Data frame of accounts with full_path populated
#' @export
gc_account_tree <- function(book_ptr) {
    .Call(`_gnucashr_gc_account_tree`, book_ptr)
}

#' Get Account by GUID (C++ Backend)
#'
#' @param book_ptr External pointer from gc_open()
#' @param guid Account GUID
#' @return Data frame with single account row, or empty data frame if not found
#' @export
gc_get_account <- function(book_ptr, guid) {
    .Call(`_gnucashr_gc_get_account`, book_ptr, guid)
}

#' Get Account by Path (C++ Backend)
#'
#' @param book_ptr External pointer from gc_open()
#' @param path Colon-separated account path
#' @return Data frame with single account row, or empty data frame if not found
#' @export
gc_get_account_by_path <- function(book_ptr, path) {
    .Call(`_gnucashr_gc_get_account_by_path`, book_ptr, path)
}

#' Get Transactions (C++ Backend)
#'
#' @param book_ptr External pointer from gc_open()
#' @param from_date Optional start date filter (YYYY-MM-DD)
#' @param to_date Optional end date filter (YYYY-MM-DD)
#' @return Data frame of transactions with splits
#' @export
gc_get_transactions <- function(book_ptr, from_date = NULL, to_date = NULL) {
    .Call(`_gnucashr_gc_get_transactions`, book_ptr, from_date, to_date)
}

#' Get Account Balance (C++ Backend)
#'
#' @param book_ptr External pointer from gc_open()
#' @param account_guid Account GUID
#' @param as_of Optional date for point-in-time balance
#' @return Numeric balance value
#' @export
gc_get_balance <- function(book_ptr, account_guid, as_of = NULL) {
    .Call(`_gnucashr_gc_get_balance`, book_ptr, account_guid, as_of)
}

#' Get Trial Balance (C++ Backend)
#'
#' @param book_ptr External pointer from gc_open()
#' @param as_of Optional date for point-in-time trial balance
#' @return Data frame with account_guid, account_name, full_path, account_type, balance
#' @export
gc_trial_balance <- function(book_ptr, as_of = NULL) {
    .Call(`_gnucashr_gc_trial_balance`, book_ptr, as_of)
}

#' Create Account (C++ Backend)
#'
#' @param book_ptr External pointer from gc_open() (must be read-write)
#' @param name Account name
#' @param type Account type string (e.g., "EXPENSE", "BANK")
#' @param parent_guid Parent account GUID
#' @param description Optional description
#' @param code Optional account code
#' @param hidden Whether account is hidden
#' @param placeholder Whether account is a placeholder
#' @return GUID of created account
#' @export
gc_create_account <- function(book_ptr, name, type, parent_guid, description = "", code = "", hidden = FALSE, placeholder = FALSE) {
    .Call(`_gnucashr_gc_create_account`, book_ptr, name, type, parent_guid, description, code, hidden, placeholder)
}

#' Post Transaction (C++ Backend)
#'
#' @param book_ptr External pointer from gc_open() (must be read-write)
#' @param description Transaction description
#' @param post_date Post date (YYYY-MM-DD HH:MM:SS)
#' @param splits_df Data frame with columns: account_guid, value_num, value_denom
#' @param num Optional transaction number
#' @return GUID of created transaction
#' @export
gc_post_transaction <- function(book_ptr, description, post_date, splits_df, num = "") {
    .Call(`_gnucashr_gc_post_transaction`, book_ptr, description, post_date, splits_df, num)
}

#' Delete Transaction (C++ Backend)
#'
#' @param book_ptr External pointer from gc_open() (must be read-write)
#' @param guid Transaction GUID
#' @export
gc_delete_transaction <- function(book_ptr, guid) {
    invisible(.Call(`_gnucashr_gc_delete_transaction`, book_ptr, guid))
}

#' Void Transaction (C++ Backend)
#'
#' @param book_ptr External pointer from gc_open() (must be read-write)
#' @param guid Transaction GUID
#' @param reason Void reason
#' @export
gc_void_transaction <- function(book_ptr, guid, reason) {
    invisible(.Call(`_gnucashr_gc_void_transaction`, book_ptr, guid, reason))
}

#' Update Split Account (C++ Backend)
#'
#' Reassign a split to a different account (for recategorization).
#'
#' @param book_ptr External pointer from gc_open() (must be read-write)
#' @param split_guid Split GUID to update
#' @param new_account_guid Target account GUID
#' @export
gc_update_split <- function(book_ptr, split_guid, new_account_guid) {
    invisible(.Call(`_gnucashr_gc_update_split`, book_ptr, split_guid, new_account_guid))
}

#' Get Splits for Account (C++ Backend)
#'
#' @param book_ptr External pointer from gc_open()
#' @param account_guid Account GUID
#' @return Data frame of splits ordered by post_date
#' @export
gc_get_splits <- function(book_ptr, account_guid) {
    .Call(`_gnucashr_gc_get_splits`, book_ptr, account_guid)
}

#' Parse CSV Bank Statement (C++ Backend)
#'
#' Parse a CSV string using a named format preset.
#'
#' @param content CSV content as string
#' @param format_name Format preset: "paypal", "stripe", "venmo", "apple_card", "generic"
#' @return Data frame with date, amount_num, amount_denom, description, memo, id, category
#' @export
gc_parse_csv <- function(content, format_name = "generic") {
    .Call(`_gnucashr_gc_parse_csv`, content, format_name)
}

#' Detect CSV Format (C++ Backend)
#'
#' Auto-detect CSV format from the header line.
#'
#' @param header_line First line of the CSV file
#' @return Format name string, or empty string if unknown
#' @export
gc_detect_csv_format <- function(header_line) {
    .Call(`_gnucashr_gc_detect_csv_format`, header_line)
}

#' Get CSV Format Info (C++ Backend)
#'
#' Return column mapping for a named format.
#'
#' @param format_name Format name: "paypal", "stripe", "venmo", "apple_card", "generic"
#' @return Named list with format details
#' @export
gc_csv_format_info <- function(format_name) {
    .Call(`_gnucashr_gc_csv_format_info`, format_name)
}

#' Get Slot Value (C++ Backend)
#'
#' Get a single slot value from the GnuCash slots table.
#'
#' @param book_ptr External pointer from gc_open()
#' @param obj_guid Entity GUID (split, account, or transaction)
#' @param name Slot name (e.g., "online_id", "notes")
#' @return Named list with slot details, or NULL if not found
#' @export
gc_get_slot <- function(book_ptr, obj_guid, name) {
    .Call(`_gnucashr_gc_get_slot`, book_ptr, obj_guid, name)
}

#' Set String Slot Value (C++ Backend)
#'
#' Set a string-typed slot on an entity. Creates or updates.
#'
#' @param book_ptr External pointer from gc_open() (must be read-write)
#' @param obj_guid Entity GUID
#' @param name Slot name
#' @param value Slot value
#' @export
gc_set_slot <- function(book_ptr, obj_guid, name, value) {
    invisible(.Call(`_gnucashr_gc_set_slot`, book_ptr, obj_guid, name, value))
}

#' Delete Slot (C++ Backend)
#'
#' @param book_ptr External pointer from gc_open() (must be read-write)
#' @param obj_guid Entity GUID
#' @param name Slot name
#' @export
gc_delete_slot <- function(book_ptr, obj_guid, name) {
    invisible(.Call(`_gnucashr_gc_delete_slot`, book_ptr, obj_guid, name))
}

#' Get All Slots for Entity (C++ Backend)
#'
#' @param book_ptr External pointer from gc_open()
#' @param obj_guid Entity GUID
#' @return Data frame of all slots
#' @export
gc_get_all_slots <- function(book_ptr, obj_guid) {
    .Call(`_gnucashr_gc_get_all_slots`, book_ptr, obj_guid)
}

#' Find Split by FITID (C++ Backend)
#'
#' Dedup check: find a split with matching online_id in the given account.
#'
#' @param book_ptr External pointer from gc_open()
#' @param account_guid Account GUID to search within
#' @param fitid FITID (Financial Institution Transaction ID)
#' @return Split GUID string, or empty string if not found
#' @export
gc_find_split_by_fitid <- function(book_ptr, account_guid, fitid) {
    .Call(`_gnucashr_gc_find_split_by_fitid`, book_ptr, account_guid, fitid)
}

#' Batch Check FITIDs (C++ Backend)
#'
#' Check which FITIDs already exist for an account.
#'
#' @param book_ptr External pointer from gc_open()
#' @param account_guid Account GUID
#' @param fitids Character vector of FITIDs to check
#' @return Data frame with columns fitid and split_guid (only matches)
#' @export
gc_check_fitids <- function(book_ptr, account_guid, fitids) {
    .Call(`_gnucashr_gc_check_fitids`, book_ptr, account_guid, fitids)
}

#' Import OFX Bank Feed (C++ Backend)
#'
#' Parse OFX content, dedup by FITID, and import transactions.
#'
#' @param book_ptr External pointer from gc_open() (must be read-write)
#' @param content OFX file content as string
#' @param target_account_guid Bank account GUID
#' @param imbalance_account_guid Imbalance/uncategorized account GUID
#' @return Named list with total_parsed, imported, duplicates, errors, imported_guids
#' @export
gc_import_ofx_feed <- function(book_ptr, content, target_account_guid, imbalance_account_guid) {
    .Call(`_gnucashr_gc_import_ofx_feed`, book_ptr, content, target_account_guid, imbalance_account_guid)
}

#' Import CSV Bank Feed (C++ Backend)
#'
#' Parse CSV content, dedup by FITID, and import transactions.
#'
#' @param book_ptr External pointer from gc_open() (must be read-write)
#' @param content CSV file content as string
#' @param format_name CSV format preset name
#' @param target_account_guid Bank account GUID
#' @param imbalance_account_guid Imbalance/uncategorized account GUID
#' @return Named list with total_parsed, imported, duplicates, errors, imported_guids
#' @export
gc_import_csv_feed <- function(book_ptr, content, format_name, target_account_guid, imbalance_account_guid) {
    .Call(`_gnucashr_gc_import_csv_feed`, book_ptr, content, format_name, target_account_guid, imbalance_account_guid)
}

#' Check Duplicate FITIDs (C++ Backend)
#'
#' @param book_ptr External pointer from gc_open()
#' @param account_guid Account GUID
#' @param fitids Character vector of FITIDs
#' @return Data frame with fitid and split_guid columns (matches only)
#' @export
gc_check_duplicates <- function(book_ptr, account_guid, fitids) {
    .Call(`_gnucashr_gc_check_duplicates`, book_ptr, account_guid, fitids)
}

#' Reconcile Account (C++ Backend)
#'
#' Mark unreconciled splits as cleared up to statement_date and compute balance.
#'
#' @param book_ptr External pointer from gc_open() (must be read-write)
#' @param account_guid Account GUID
#' @param statement_date Statement date (YYYY-MM-DD)
#' @param statement_balance Expected balance as double
#' @return Named list with splits_reconciled, statement_balance, book_balance,
#'   difference, balanced
#' @export
gc_reconcile_account <- function(book_ptr, account_guid, statement_date, statement_balance) {
    .Call(`_gnucashr_gc_reconcile_account`, book_ptr, account_guid, statement_date, statement_balance)
}

#' Find Cross-Institution Transfer Matches (C++ Backend)
#'
#' Find potential transfer matches between two accounts based on
#' inverted amounts, date proximity, and description similarity.
#'
#' @param book_ptr External pointer from gc_open()
#' @param account_a_guid First account GUID
#' @param account_b_guid Second account GUID
#' @param from_date Start date (YYYY-MM-DD)
#' @param to_date End date (YYYY-MM-DD)
#' @param date_window Max days between matching transactions (default 3)
#' @param min_similarity Minimum match confidence 0-1 (default 0.5)
#' @return Data frame with match details
#' @export
gc_find_transfer_matches <- function(book_ptr, account_a_guid, account_b_guid, from_date, to_date, date_window = 3L, min_similarity = 0.5) {
    .Call(`_gnucashr_gc_find_transfer_matches`, book_ptr, account_a_guid, account_b_guid, from_date, to_date, date_window, min_similarity)
}

#' Resolve Identity (C++ Backend)
#'
#' Determine the current user identity using CLI flag, GNUCASH_USER env,
#' or system username fallback.
#'
#' @param cli_identity Optional identity override (e.g. from CLI flag)
#' @return Named list with user_id, display_name, node_name, source
#' @export
gc_resolve_identity <- function(cli_identity = NULL) {
    .Call(`_gnucashr_gc_resolve_identity`, cli_identity)
}

#' Get System Username (C++ Backend)
#'
#' @return System username string
#' @export
gc_system_username <- function() {
    .Call(`_gnucashr_gc_system_username`)
}

#' Open Audit Database (C++ Backend)
#'
#' Opens or creates an audit database for a GnuCash book.
#' The database is stored at <book_path>.audit.db.
#'
#' @param book_path Path to the GnuCash book file
#' @return External pointer to AuditLogger object
#' @export
gc_audit_open <- function(book_path) {
    .Call(`_gnucashr_gc_audit_open`, book_path)
}

#' Close Audit Database (C++ Backend)
#'
#' @param audit_ptr External pointer from gc_audit_open()
#' @export
gc_audit_close <- function(audit_ptr) {
    invisible(.Call(`_gnucashr_gc_audit_close`, audit_ptr))
}

#' Log Audit Record (C++ Backend)
#'
#' @param audit_ptr External pointer from gc_audit_open()
#' @param tool_name MCP tool name
#' @param book_path GnuCash file path
#' @param classification "read" or "write"
#' @param result_status "success" or "error"
#' @param entity_guid Optional entity GUID
#' @param error_message Optional error message
#' @param duration_ms Optional execution time in milliseconds
#' @export
gc_audit_log <- function(audit_ptr, tool_name, book_path, classification = "read", result_status = "success", entity_guid = NULL, error_message = NULL, duration_ms = NULL) {
    invisible(.Call(`_gnucashr_gc_audit_log`, audit_ptr, tool_name, book_path, classification, result_status, entity_guid, error_message, duration_ms))
}

#' Query Audit Log (C++ Backend)
#'
#' @param audit_ptr External pointer from gc_audit_open()
#' @param since Optional start timestamp (ISO 8601)
#' @param until Optional end timestamp (ISO 8601)
#' @param tool_name Optional tool name filter
#' @param limit Maximum records to return (default 100)
#' @return Data frame of audit records
#' @export
gc_audit_query <- function(audit_ptr, since = NULL, until = NULL, tool_name = NULL, limit = 100L) {
    .Call(`_gnucashr_gc_audit_query`, audit_ptr, since, until, tool_name, limit)
}

#' Export Audit Log in Aperture Format (C++ Backend)
#'
#' Export audit records as JSONL compatible with Tailscale Aperture.
#'
#' @param audit_ptr External pointer from gc_audit_open()
#' @param since Optional start timestamp (ISO 8601)
#' @param until Optional end timestamp (ISO 8601)
#' @param limit Maximum records (default 100)
#' @return JSONL string
#' @export
gc_audit_export_aperture <- function(audit_ptr, since = NULL, until = NULL, limit = 100L) {
    .Call(`_gnucashr_gc_audit_export_aperture`, audit_ptr, since, until, limit)
}

#' Open Agent State Database (C++ Backend)
#'
#' Opens or creates a per-agent state database.
#' Stored at <book_path>.agent.<agent_name>.db.
#'
#' @param book_path Path to the GnuCash book file
#' @param agent_name Agent identifier (e.g. "spend-monitor")
#' @return External pointer to AgentStateDB object
#' @export
gc_agent_state_open <- function(book_path, agent_name) {
    .Call(`_gnucashr_gc_agent_state_open`, book_path, agent_name)
}

#' Close Agent State Database (C++ Backend)
#'
#' @param state_ptr External pointer from gc_agent_state_open()
#' @export
gc_agent_state_close <- function(state_ptr) {
    invisible(.Call(`_gnucashr_gc_agent_state_close`, state_ptr))
}

#' Set Agent State Value (C++ Backend)
#'
#' @param state_ptr External pointer from gc_agent_state_open()
#' @param key State key
#' @param value State value
#' @export
gc_agent_state_set <- function(state_ptr, key, value) {
    invisible(.Call(`_gnucashr_gc_agent_state_set`, state_ptr, key, value))
}

#' Get Agent State Value (C++ Backend)
#'
#' @param state_ptr External pointer from gc_agent_state_open()
#' @param key State key
#' @return Value string, or NULL if key not found
#' @export
gc_agent_state_get <- function(state_ptr, key) {
    .Call(`_gnucashr_gc_agent_state_get`, state_ptr, key)
}

#' Enqueue Review Item (C++ Backend)
#'
#' Add a transaction categorization suggestion to the review queue.
#'
#' @param state_ptr External pointer from gc_agent_state_open()
#' @param transaction_guid Transaction GUID
#' @param suggested_category Target account path
#' @param confidence Confidence score 0-1
#' @param reason Reasoning for the suggestion
#' @return Integer ID of the created review item
#' @export
gc_agent_state_enqueue_review <- function(state_ptr, transaction_guid, suggested_category, confidence, reason) {
    .Call(`_gnucashr_gc_agent_state_enqueue_review`, state_ptr, transaction_guid, suggested_category, confidence, reason)
}

#' Get Pending Reviews (C++ Backend)
#'
#' @param state_ptr External pointer from gc_agent_state_open()
#' @param limit Maximum items to return (default 50)
#' @return Data frame of pending review items
#' @export
gc_agent_state_pending_reviews <- function(state_ptr, limit = 50L) {
    .Call(`_gnucashr_gc_agent_state_pending_reviews`, state_ptr, limit)
}

#' Update Review Status (C++ Backend)
#'
#' @param state_ptr External pointer from gc_agent_state_open()
#' @param id Review item ID
#' @param status New status: "pending", "approved", or "rejected"
#' @export
gc_agent_state_update_review <- function(state_ptr, id, status) {
    invisible(.Call(`_gnucashr_gc_agent_state_update_review`, state_ptr, id, status))
}

#' Classify MCP Tool Authorization Level (C++ Backend)
#'
#' @param tool_name MCP tool name (e.g., "gnucash_post_transaction")
#' @return String: "auto", "review", or "approve"
#' @export
gc_classify_tool <- function(tool_name) {
    .Call(`_gnucashr_gc_classify_tool`, tool_name)
}

#' Run Security Check (C++ Backend)
#'
#' @param policy_list R list with enforcement_enabled, agent_name, agent_tier, rules
#' @param tool_name MCP tool name
#' @param arguments_json JSON string of tool arguments
#' @return Named list: decision, reason, approval_id (or NULL)
#' @export
gc_security_check <- function(policy_list, tool_name, arguments_json) {
    .Call(`_gnucashr_gc_security_check`, policy_list, tool_name, arguments_json)
}

#' Create Rate Limiter (C++ Backend)
#'
#' @return External pointer to a RateLimiter
#' @export
gc_rate_limiter_create <- function() {
    .Call(`_gnucashr_gc_rate_limiter_create`)
}

#' Check Rate Limit (C++ Backend)
#'
#' @param limiter_ptr External pointer from gc_rate_limiter_create()
#' @param agent Agent identifier
#' @param operation Operation name
#' @param max_per_hour Maximum calls allowed per hour
#' @return Named list: allowed (logical), remaining (integer)
#' @export
gc_rate_limiter_check <- function(limiter_ptr, agent, operation, max_per_hour) {
    .Call(`_gnucashr_gc_rate_limiter_check`, limiter_ptr, agent, operation, max_per_hour)
}

#' Check Transaction Anomaly (C++ Backend)
#'
#' @param arguments_json JSON string of tool arguments
#' @param amount_threshold Anomaly threshold in cents (default 500000 = $5000)
#' @return Named list: is_anomalous, reason, severity
#' @export
gc_check_anomaly <- function(arguments_json, amount_threshold = 500000) {
    .Call(`_gnucashr_gc_check_anomaly`, arguments_json, amount_threshold)
}

#' Open Approval Database (C++ Backend)
#'
#' @param book_path Path to GnuCash file (approval DB at <book>.approvals.db)
#' @return External pointer to ApprovalDB
#' @export
gc_approval_open <- function(book_path) {
    .Call(`_gnucashr_gc_approval_open`, book_path)
}

#' Close Approval Database (C++ Backend)
#'
#' @param approval_ptr External pointer from gc_approval_open()
#' @export
gc_approval_close <- function(approval_ptr) {
    invisible(.Call(`_gnucashr_gc_approval_close`, approval_ptr))
}

#' Create Approval Request (C++ Backend)
#'
#' @param approval_ptr External pointer from gc_approval_open()
#' @param agent_name Agent creating the request
#' @param tool_name Tool requiring approval
#' @param arguments_json JSON string of tool arguments
#' @param requesting_user User identity
#' @param reason Why approval is needed
#' @return Request ID (GUID string)
#' @export
gc_approval_create <- function(approval_ptr, agent_name, tool_name, arguments_json, requesting_user, reason) {
    .Call(`_gnucashr_gc_approval_create`, approval_ptr, agent_name, tool_name, arguments_json, requesting_user, reason)
}

#' List Pending Approval Requests (C++ Backend)
#'
#' @param approval_ptr External pointer from gc_approval_open()
#' @param limit Maximum number of requests to return
#' @return Data frame of pending requests
#' @export
gc_approval_pending <- function(approval_ptr, limit = 50L) {
    .Call(`_gnucashr_gc_approval_pending`, approval_ptr, limit)
}

#' Approve a Pending Request (C++ Backend)
#'
#' @param approval_ptr External pointer from gc_approval_open()
#' @param id Request ID to approve
#' @param approver Identity of the approver
#' @export
gc_approval_approve <- function(approval_ptr, id, approver) {
    invisible(.Call(`_gnucashr_gc_approval_approve`, approval_ptr, id, approver))
}

#' Reject a Pending Request (C++ Backend)
#'
#' @param approval_ptr External pointer from gc_approval_open()
#' @param id Request ID to reject
#' @param approver Identity of the approver
#' @param reason Reason for rejection
#' @export
gc_approval_reject <- function(approval_ptr, id, approver, reason) {
    invisible(.Call(`_gnucashr_gc_approval_reject`, approval_ptr, id, approver, reason))
}

#' Get a Specific Approval Request (C++ Backend)
#'
#' @param approval_ptr External pointer from gc_approval_open()
#' @param id Request ID
#' @return Named list or NULL if not found
#' @export
gc_approval_get <- function(approval_ptr, id) {
    .Call(`_gnucashr_gc_approval_get`, approval_ptr, id)
}

#' Generate GnuCash-Format GUID
#'
#' Generate a random 32-character hex GUID in GnuCash format.
#' GnuCash uses lowercase hex without dashes.
#'
#' @return Character string with 32-character hex GUID
#' @export
generate_guid <- function() {
    .Call(`_gnucashr_generate_guid`)
}

#' Validate GnuCash GUID Format
#'
#' Check if a string is a valid 32-character hex GUID.
#'
#' @param guid Character string to validate
#' @return Logical indicating validity
#' @export
validate_guid <- function(guid) {
    .Call(`_gnucashr_validate_guid`, guid)
}

#' Generate Multiple GUIDs
#'
#' Vectorized GUID generation for batch operations.
#'
#' @param n Number of GUIDs to generate
#' @return CharacterVector of GUIDs
#' @export
generate_guids <- function(n) {
    .Call(`_gnucashr_generate_guids`, n)
}

#' Parallel Monte Carlo Simulation
#'
#' Run Monte Carlo simulation for financial projections using parallel execution.
#' Uses RcppParallel with thread-local RNG for reproducible, deterministic results.
#'
#' @param base_revenue Starting monthly revenue
#' @param base_expense_rate Base expense ratio (0-1)
#' @param n_sims Number of simulations to run (default 10000)
#' @param n_periods Number of periods to project (default 12)
#' @param growth_mean Mean monthly growth rate (default 0.05 = 5%)
#' @param growth_sd Standard deviation of growth (default 0.03)
#' @param expense_mean Mean expense ratio (default matches base_expense_rate)
#' @param expense_sd Standard deviation of expense ratio (default 0.05)
#' @param seed Master seed for reproducibility (default 42)
#' @return List with: results (matrix), final_cash (vector), summary (quantiles)
#' @export
monte_carlo_parallel <- function(base_revenue, base_expense_rate, n_sims = 10000L, n_periods = 12L, growth_mean = 0.05, growth_sd = 0.03, expense_mean = -1.0, expense_sd = 0.05, seed = 42L) {
    .Call(`_gnucashr_monte_carlo_parallel`, base_revenue, base_expense_rate, n_sims, n_periods, growth_mean, growth_sd, expense_mean, expense_sd, seed)
}

#' Multi-Entity Parallel Monte Carlo
#'
#' Run Monte Carlo simulation for multiple entities with correlated growth.
#'
#' @param base_revenues NumericVector of starting revenues per entity
#' @param growth_means NumericVector of mean growth rates per entity
#' @param growth_sds NumericVector of growth standard deviations per entity
#' @param expense_rates NumericVector of expense ratios per entity
#' @param n_sims Number of simulations (default 10000)
#' @param n_periods Number of periods (default 12)
#' @param seed Master seed for reproducibility
#' @return List with entity_results, total_cash, and summary
#' @export
monte_carlo_multi_entity <- function(base_revenues, growth_means, growth_sds, expense_rates, n_sims = 10000L, n_periods = 12L, seed = 42L) {
    .Call(`_gnucashr_monte_carlo_multi_entity`, base_revenues, growth_means, growth_sds, expense_rates, n_sims, n_periods, seed)
}

#' Detect OFX File Version
#'
#' Determine whether an OFX file is version 1.x (SGML) or 2.x (XML).
#'
#' @param content String content of the OFX file
#' @return String: "1" for SGML, "2" for XML, "unknown" otherwise
#' @export
detect_ofx_version_cpp <- function(content) {
    .Call(`_gnucashr_detect_ofx_version_cpp`, content)
}

#' Parse OFX Content
#'
#' Parse OFX/QFX file content and extract transaction data.
#' Handles both OFX 1.x (SGML) and 2.x (XML) formats.
#'
#' @param content String content of the OFX file
#' @return List with vectors: dates, amounts, names, fitids, memos, trntype, currency
#' @export
parse_ofx_cpp <- function(content) {
    .Call(`_gnucashr_parse_ofx_cpp`, content)
}

#' Extract OFX Account Info
#'
#' Extract account information from OFX content (ACCTID, BANKID, etc.)
#'
#' @param content String content of the OFX file
#' @return List with account_id, bank_id, account_type, org_name
#' @export
extract_ofx_account_info <- function(content) {
    .Call(`_gnucashr_extract_ofx_account_info`, content)
}

#' Parallel Scenario Projection
#'
#' Project multiple growth scenarios in parallel for each entity.
#'
#' @param base_values Starting values per entity
#' @param growth_matrix Matrix of growth rates (scenarios x entities)
#' @param n_periods Number of periods to project
#' @return List with results matrix, final totals, and metadata
#' @export
parallel_project_scenarios <- function(base_values, growth_matrix, n_periods = 12L) {
    .Call(`_gnucashr_parallel_project_scenarios`, base_values, growth_matrix, n_periods)
}

#' Parallel Sensitivity Grid
#'
#' Compute sensitivity grid for growth rate and expense ratio combinations.
#' Efficient for large parameter sweeps.
#'
#' @param base_revenue Starting revenue
#' @param base_expense_rate Base expense ratio
#' @param growth_range Vector of growth rates to test
#' @param expense_range Vector of expense ratios to test
#' @param n_periods Number of periods to project
#' @return List with outcomes matrix and ranges
#' @export
parallel_sensitivity_grid <- function(base_revenue, base_expense_rate, growth_range, expense_range, n_periods = 12L) {
    .Call(`_gnucashr_parallel_sensitivity_grid`, base_revenue, base_expense_rate, growth_range, expense_range, n_periods)
}

#' Batch Growth Projection
#'
#' Project growth for many initial values with same parameters.
#' Useful for account-level projections.
#'
#' @param initial_values Vector of starting values
#' @param growth_rate Monthly growth rate
#' @param expense_rate Expense ratio (0-1)
#' @param n_periods Number of periods
#' @return List with projections matrix and final values
#' @export
batch_project_growth <- function(initial_values, growth_rate, expense_rate, n_periods = 12L) {
    .Call(`_gnucashr_batch_project_growth`, initial_values, growth_rate, expense_rate, n_periods)
}

#' Sequential Projection (Non-Parallel Fallback)
#'
#' Single-threaded projection for testing and comparison.
#'
#' @param base_revenue Starting revenue
#' @param growth_rate Monthly growth rate
#' @param expense_rate Expense ratio
#' @param n_periods Number of periods
#' @return NumericVector of cumulative cash by period
#' @export
sequential_projection <- function(base_revenue, growth_rate, expense_rate, n_periods = 12L) {
    .Call(`_gnucashr_sequential_projection`, base_revenue, growth_rate, expense_rate, n_periods)
}

#' Validate Transaction Balance
#'
#' Check that a set of split values sum to zero (double-entry principle).
#' Uses exact integer arithmetic to avoid floating-point errors.
#'
#' @param value_nums Integer vector of split value numerators
#' @param value_denoms Integer vector of split value denominators
#' @param tolerance Maximum allowed imbalance (default 0, strict)
#' @return List with: balanced (bool), total (double), message (string)
#' @export
validate_transaction_balance <- function(value_nums, value_denoms, tolerance = 0.0) {
    .Call(`_gnucashr_validate_transaction_balance`, value_nums, value_denoms, tolerance)
}

#' Validate Account GUID Format
#'
#' Check if a string is a valid GnuCash GUID (32 hex characters).
#'
#' @param guids Character vector of GUIDs to validate
#' @return Logical vector indicating validity
#' @export
validate_guids <- function(guids) {
    .Call(`_gnucashr_validate_guids`, guids)
}

#' Check for Duplicate GUIDs
#'
#' Verify that all GUIDs in a vector are unique.
#'
#' @param guids Character vector of GUIDs
#' @return List with: unique (bool), duplicates (character vector)
#' @export
check_guid_uniqueness <- function(guids) {
    .Call(`_gnucashr_check_guid_uniqueness`, guids)
}

#' Validate Split Values
#'
#' Check that split values are valid (non-zero, proper fractions).
#'
#' @param value_nums Integer vector of numerators
#' @param value_denoms Integer vector of denominators
#' @return List with validation results
#' @export
validate_split_values <- function(value_nums, value_denoms) {
    .Call(`_gnucashr_validate_split_values`, value_nums, value_denoms)
}

#' Calculate Running Balance
#'
#' Calculate running balance for a series of transactions.
#' Optimized for large transaction histories.
#'
#' @param value_nums Integer vector of value numerators
#' @param value_denoms Integer vector of value denominators
#' @param opening_balance Starting balance (default 0)
#' @return NumericVector of running balances
#' @export
calculate_running_balance <- function(value_nums, value_denoms, opening_balance = 0.0) {
    .Call(`_gnucashr_calculate_running_balance`, value_nums, value_denoms, opening_balance)
}

